/*
 * Decompiled with CFR 0.152.
 */
import java.io.InputStream;

public class mResources {
    public int[] imgId = new int[3];
    public static String nameHienThi;
    public static int[] listPort;
    public static String[] listIP;
    public static int[] serverST;
    public static String[] listName;
    public static byte[] serverLoginList;
    public static int languageID;
    public static String gameAI;
    public static String gameAJ;
    public static String gameAK;
    public static String gameAL;
    public static String gameAM;
    public static String gameAN;
    public static String gameAO;
    public static String gameAP;
    public static String gameAQ;
    public static String gameAR;
    public static String gameAS;
    public static String gameAT;
    public static String gameAU;
    public static String gameAV;
    public static String gameAW;
    public static String gameAX;
    public static String gameAY;
    public static String gameAZ;
    public static String gameBA;
    public static String gameBB;
    public static String gameBC;
    public static String gameBD;
    public static String gameBE;
    public static String[] tips;
    public static String gameBG;
    public static String gameBH;
    public static String gameBI;
    public static String gameBJ;
    public static String gameBK;
    public static String LANGUAGE;
    public static String gameBM;
    public static String[] LANGUAGES;
    public static String gameBO;
    public static String CLOSE;
    public static String gameBQ;
    public static String gameBR;
    public static String gameBS;
    public static String gameBT;
    public static String gameBU;
    public static String gameBV;
    public static String gameBW;
    public static String gameBX;
    public static String gameBY;
    public static String gameBZ;
    public static String gameCA;
    public static String gameCB;
    public static String gameCC;
    public static String gameCD;
    public static String DELETE;
    public static String gameCF;
    public static String gameCG;
    public static String gameCH;
    public static String gameCI;
    public static String gameCJ;
    public static String gameCK;
    public static String gameCL;
    public static String gameCM;
    public static String gameCN;
    public static String gameCO;
    public static String YES;
    public static String gameCQ;
    public static String gameCR;
    public static String gameCS;
    public static String gameCT;
    public static String gameCU;
    public static String gameCV;
    public static String gameCW;
    public static String gameCX;
    public static String gameCY;
    public static String gameCZ;
    public static String gameDA;
    public static String gameDB;
    public static String NO;
    public static String EXIT;
    public static String CHAT;
    public static String OK;
    public static String USERNAME;
    public static String PASSWORD;
    public static String REPASS;
    public static String gameDJ;
    public static String gameDK;
    public static String gameDL;
    public static String RESTART;
    public static String REPASSWORD;
    public static String REMEMBER;
    public static String UNCHECK;
    public static String gameDQ;
    public static String gameDR;
    public static String gameDS;
    public static String NOT_INPUT_USERNAME;
    public static String NOT_SPEC_CHARACTER;
    public static String NOT_INPUT_PASS1;
    public static String NOT_INPUT_PASS2;
    public static String USERNAME_LENGHT;
    public static String WRONG_PASSWORD;
    public static String[] REGISTER_TEXT;
    public static String gameEA;
    public static String ASK_REG_NUM;
    public static String gameEC;
    public static String[] gameED;
    public static String gameEE;
    public static String gameEF;
    public static String gameEG;
    public static String gameEH;
    public static String ACCEPT;
    public static String CANCEL;
    public static String gameEK;
    public static String gameEL;
    public static String gameEM;
    public static String gameEN;
    public static String gameEO;
    public static String CONNECTING;
    public static String REGISTERING;
    public static String LOGGING;
    public static String gameES;
    public static String gameET;
    public static String gameEU;
    public static String SELECT;
    public static String gameEW;
    public static String gameEX;
    public static String gameEY;
    public static String gameEZ;
    public static String gameFA;
    public static String gameFB;
    public static String gameFC;
    public static String gameFD;
    public static String gameFE;
    public static String gameFF;
    public static String gameFG;
    public static String CHARNAME;
    public static String gameFI;
    public static String gameFJ;
    public static String gameFK;
    public static String gameFL;
    public static String gameFM;
    public static String gameFN;
    public static String gameFO;
    public static String gameFP;
    public static String gameFQ;
    public static String gameFR;
    public static String gameFS;
    public static String gameFT;
    public static String gameFU;
    public static String gameFV;
    public static String gameFW;
    public static String[] gameFX;
    public static String gameFY;
    public static String gameFZ;
    public static String gameGA;
    public static String gameGB;
    public static String gameGC;
    public static String gameGD;
    public static String gameGE;
    public static String gameGF;
    public static String gameGG;
    public static String CHANGE;
    public static String gameGI;
    public static String gameGJ;
    public static String[] gameGK;
    public static String[] gameGL;
    public static String[][] HAIR_STYLE;
    public static String[] gameGN;
    public static String[] gameGO;
    public static String[] gameGP;
    public static String[] gameGQ;
    public static String[] gameGR;
    public static String[] gameGS;
    public static String[] gameGT;
    public static String[] gameGU;
    public static String[] gameGV;
    public static String[] gameGW;
    public static String[] gameGX;
    public static String[] gameGY;
    public static String[] gameGZ;
    public static String[] gameHA;
    public static String[] gameHB;
    public static String[] gameHC;
    public static String[] gameHD;
    public static String[] gameHE;
    public static String[] gameHF;
    public static String[] gameHG;
    public static String[] gameHH;
    public static String[] gameHI;
    public static String[] gameHJ;
    public static String[] gameHK;
    public static String[] gameHL;
    public static String[] gameHM;
    public static String[] gameHN;
    public static String[] gameHO;
    public static String[] gameHP;
    public static String[] gameHQ;
    public static String[] gameHR;
    public static String[] gameHS;
    public static String[] gameHT;
    public static String[] gameHU;
    public static String[] gameHV;
    public static String[] gameHW;
    public static String gameHX;
    public static String gameHY;
    public static String gameHZ;
    public static String gameKA;
    public static String gameKB;
    public static String gameKC;
    public static String gameKD;
    public static String gameKE;
    public static String gameKF;
    public static String gameKG;
    public static String gameKH;
    public static String gameKI;
    public static String gameKJ;
    public static String gameKK;
    public static String gameKL;
    public static String gameKM;
    public static String gameKN;
    public static String gameKO;
    public static String gameKP;
    public static String gameKQ;
    public static String gameKR;
    public static String gameKS;
    public static String gameKT;
    public static String gameKU;
    public static String gameKV;
    public static String gameKW;
    public static String gameKX;
    public static String gameKY;
    public static String gameKZ;
    public static String gameMA;
    public static String[] gameMB;
    public static String ME_TASK;
    public static String gameMD;
    public static String gameME;
    public static String gameMF;
    public static String gameMG;
    public static String gameMH;
    public static String gameMI;
    public static String gameMJ;
    public static String[] gameMK;
    public static String gameML;
    public static String gameMM;
    public static String gameMN;
    public static String gameMO;
    public static String gameMP;
    public static String gameMQ;
    public static String[] gameMR;
    public static String[] gameMS;
    public static String[] gameMT;
    public static String gameMU;
    public static String[] gameMV;
    public static String[] gameMW;
    public static String[] gameMX;
    public static String[] MENUGENDER;
    public static String[] gameMZ;
    public static String gameNA;
    public static String gameNB;
    public static String gameNC;
    public static String gameND;
    public static String[] gameNE;
    public static String gameNF;
    public static String gameNG;
    public static String gameNH;
    public static String gameNI;
    public static String gameNJ;
    public static String gameNK;
    public static String gameNL;
    public static String gameNM;
    public static String gameNN;
    public static String gameNO;
    public static String gameNP;
    public static String gameNQ;
    public static String gameNR;
    public static String gameNS;
    public static String gameNT;
    public static String gameNU;
    public static String gameNV;
    public static String gameNW;
    public static String gameNX;
    public static String gameNY;
    public static String gameNZ;
    public static String gamePA;
    public static String gamePB;
    public static String gamePC;
    public static String INPUT_NICK;
    public static String gamePE;
    public static String gamePF;
    public static String gamePG;
    public static String gamePH;
    public static String gamePI;
    public static String gamePJ;
    public static String gamePK;
    public static String gamePL;
    public static String gamePM;
    public static String[][] gamePN;
    public static String[] gamePO;
    public static String[] gamePP;
    public static String gamePQ;
    public static String gamePR;
    public static String gamePS;
    public static String gamePT;
    public static String gamePU;
    public static String gamePV;
    public static String gamePW;
    public static String[] gamePX;
    public static String[] gamePY;
    public static String MONTH;
    public static String WEEK;
    public static String DAY;
    public static String HOUR;
    public static String gameQD;
    public static String MINUTE;
    public static String gameQF;
    public static String gameQG;
    public static String gameQH;
    public static String gameQI;
    public static String gameQJ;
    public static String gameQK;
    public static String gameQL;
    public static String gameQM;
    public static String gameQN;
    public static String gameQO;
    public static String gameQP;
    public static String gameQQ;
    public static String gameQR;
    public static String gameQS;
    public static String gameQT;
    public static String gameQU;
    public static String gameQV;
    public static String gameQW;
    public static String gameQX;
    public static String gameQY;
    public static String gameQZ;
    public static String gameRA;
    public static String gameRB;
    public static String gameRC;
    public static String gameRD;
    public static String gameRE;
    public static String gameRF;
    public static String[] gameRG;
    public static String gameRH;
    public static String gameRI;
    public static String gameRJ;
    public static String gameRK;
    public static String gameRL;
    public static String[] gameRM;
    public static String[] gameRN;
    public static String[] CLAN_ACTIVITY;
    public static String gameRP;
    public static String gameRQ;
    public static String[][] gameRR;
    public static String[] gameRS;
    public static String[] gameRT;
    public static String[] gameRU;
    public static String[] CHARINGFO;
    public static String gameRW;
    public static String gameRX;
    public static String gameRY;
    public static String gameRZ;
    public static String gameSA;
    public static String gameSB;
    public static String gameSC;
    public static String gameSD;
    public static String gameSE;
    public static String gameSF;
    public static String[] gameSG;
    public static String gameSH;
    public static String[] gameSI;
    public static String[] gameSJ;
    public static String gameSK;
    public static String gameSL;
    public static String gameSM;
    public static String gameSN;
    public static String gameSO;
    public static String gameSP;
    public static String gameSQ;
    public static String gameSR;
    public static String gameSS;
    public static String gameST;
    public static String gameSU;
    public static String[] gameSV;
    public static String[] gameSW;
    public static String[] gameSX;
    public static String[] gameSY;
    public static String[] gameSZ;
    public static String[] gameTA;
    public static String gameTB;
    public static String[] gameTC;
    public static String gameTD;
    public static String gameTE;
    public static String gameTF;
    public static String gameTG;
    public static String gameTH;
    public static String gameTI;
    public static String[] gameTJ;
    public static String[] gameTK;
    public static String[] gameTL;
    public static String CLOSE_CURTAB;
    public static String[] PUBLICCHAT;
    public static String[] PARTYCHAT;
    public static String[] GLOBALCHAT;
    public static String[] CLANCHAT;
    public static String gameTR;
    public static String gameTS;
    public static String gameTT;
    public static String gameTU;
    public static String gameTV;
    public static String gameTW;
    public static String gameTX;
    public static String gameTY;
    public static String gameTZ;
    public static String gameUA;
    public static String gameUB;
    public static String gameUC;
    public static String gameUD;
    public static String gameUE;
    public static String gameUF;
    public static String gameUG;
    public static String gameUH;
    public static String gameUI;
    public static String gameUJ;
    public static String gameUK;
    public static String gameUL;
    public static String gameUM;
    public static String gameUN;
    public static String gameUO;
    public static String gameUP;
    public static String gameUQ;
    public static String gameUR;
    public static String gameUS;
    public static String gameUT;
    public static String gameUU;
    public static String gameUV;
    public static String gameUW;
    public static String[] gameUX;
    public static String gameUY;
    public static String gameUZ;
    public static String gameVA;
    public static String gameVB;
    public static String gameVC;
    public static String gameVD;
    public static String gameVE;
    public static String gameVF;
    public static String gameVG;
    public static String gameVH;
    public static String gameVI;
    public static String gameVJ;
    public static String gameVK;
    public static String gameVL;
    public static String gameVM;
    public static String gameVN;
    public static String gameVO;
    public static String gameVP;
    public static String gameVQ;
    public static String gameVR;
    public static String[] gameVS;
    public static String gameVT;
    public static String gameVU;
    public static String gameVV;
    public static String gameVW;
    public static String gameVX;
    public static String gameVY;
    public static String gameVZ;
    public static String gameWA;
    public static String gameWB;
    public static String gameWC;
    public static String[][] gameWD;
    public static String[] gameWE;
    public static String gameWF;
    public static String gameWG;
    public static String gameWH;
    public static String gameWI;
    public static String[] gameWJ;
    public static String[] gameWK;
    public static String gameWL;
    public static String gameWM;
    public static String gameWN;
    public static String[] gameWO;
    public static String gameWP;
    public static String gameWQ;
    public static String gameWR;
    public static String gameWS;
    public static String gameWT;
    public static String gameWU;
    public static String gameWV;
    public static String gameWW;
    public static String gameWX;
    public static String gameWY;
    public static String gameWZ;
    public static String gameXA;
    public static String gameXB;
    public static String gameXC;
    public static String gameXD;
    public static String gameXE;
    public static String[] gameXF;
    public static String gameXG;
    public static String NEW_ACC_ARLET;
    public static String NEW_PLAY;
    public static String COUNTINUE_PLAY;
    public static String CHANGE_ACC;
    public static String SERVER;
    public static String COUNTINUE;
    public static String[] gameXN;
    public static String gameXO;
    public static String gameXP;

    public static void gameAA() {
        String var0 = mResources.gameAA("hd.txt");
        GameScr.gI().gameAA("H\u01b0\u1edbng d\u1eabn", var0, false);
    }

    private static String gameAA(String var0) {
        InputStream var3 = RMS.gameAA("/" + var0);
        try {
            byte[] var1 = new byte[var3.available()];
            var3.read(var1);
            var0 = new String(var1, "UTF-8");
        }
        catch (Exception var2) {
            var0 = "";
        }
        return var0;
    }

    public static void gameAB() {
        if (languageID == 0) {
            gameAJ = "Vi\u00ean ng\u1ecdc n\u00e0y kh\u00f4ng th\u1ec3 g\u1ecdt.";
            gameAI = "Vi\u00ean ng\u1ecdc \u0111\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a.";
            gameAK = "\u0110\u0103ng k\u00fd m\u1ed9t t\u00e0i kho\u1ea3n s\u1ebd gi\u00fap nh\u00e2n v\u1eadt \u0111ang ch\u01a1i c\u1ee7a b\u1ea1n c\u00f2n m\u00e3i. B\u1ea1n c\u00f3 mu\u1ed1n \u0111\u0103ng k\u00fd kh\u00f4ng?";
            gameAL = "Nhi\u1ec7m v\u1ee5 b\u00ed \u1ea9n";
            gameAM = "- N\u00e2ng hi\u1ebfu chi\u1ebfn l\u00ean 1.";
            gameAN = "- Ho\u00e0n th\u00e0nh hang \u0111\u1ed9ng 1 l\u1ea7n.";
            gameAO = "- Ho\u00e0n th\u00e0nh t\u00e0 th\u00fa 1 l\u1ea7n.";
            gameAP = "- Ho\u00e0n th\u00e0nh 1 l\u1ea7n n\u00e2ng c\u1ea5p.";
            gameAQ = "- Ho\u00e0n th\u00e0nh 10 nhi\u1ec7m v\u1ee5 h\u00e0ng ng\u00e0y.";
            gameAR = "- L\u1ea5y 1000 \u0111i\u1ec3m chi\u1ebfn tr\u01b0\u1eddng.";
            gameAS = "- Ho\u00e0n th\u00e0nh 1 l\u1ea7n th\u1ea5t th\u00fa \u1ea3i.";
            gameAT = "- Ho\u00e0n th\u00e0nh 3 l\u1ea7n quay s\u1ed1.";
            String[] var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "Li\u00ean Server"};
            gameAW = "T\u1ec9 l\u1ec7 th\u1eafng";
            gameAX = "B\u1ea1n \u0111\u00e3 tham gia: ";
            gameAY = "S\u1ed1 ng\u01b0\u1eddi tham gia: ";
            gameAZ = "V\u00f2ng xoay may m\u1eafn";
            gameBA = "Tham gia";
            COUNTINUE = "Ti\u1ebfp t\u1ee5c";
            NEW_ACC_ARLET = "T\u00e0i kho\u1ea3n c\u1ee7a b\u1ea1n ch\u01b0a \u0111\u01b0\u1ee3c x\u00e1c th\u1ef1c. N\u1ebfu b\u1ea1n x\u00f3a tr\u00f2 ch\u01a1i, ho\u1eb7c \u0111\u0103ng nh\u1eadp t\u00e0i kho\u1ea3n kh\u00e1c, nh\u00e2n v\u1eadt \u0111ang ch\u01a1i c\u1ee7a b\u1ea1n s\u1ebd m\u1ea5t v\u0129nh vi\u1ec5n.";
            NEW_PLAY = "Ch\u01a1i m\u1edbi";
            COUNTINUE_PLAY = "Ch\u01a1i ti\u1ebfp";
            CHANGE_ACC = "\u0110\u1ed5i t\u00e0i kho\u1ea3n";
            SERVER = "M\u00e1y Ch\u1ee7: ";
            gameBB = "h\u1ea1ng";
            gameBC = "Th\u00e1ch \u0110\u1ea5u";
            gameBD = "Th\u00f4ng tin";
            tips = new String[]{"B\u1ea1n c\u00f3 th\u1ec3 nh\u1ea5n gi\u1eef n\u00fat chuy\u1ec3n m\u1ee5c ti\u00eau \u0111\u1ec3 hi\u1ec3n th\u1ecb danh s\u00e1ch ng\u01b0\u1eddi ch\u01a1i kh\u00e1c trong map", "\u0110\u1ed1i v\u1edbi m\u00e1y c\u00f3 b\u00e0n ph\u00edm, b\u1ea1n c\u00f3 th\u1ec3 g\u00e1n ph\u00edm t\u1eaft cho c\u00e1c ph\u00edm 7,8,9 ho\u1eb7c Q,W,E \u0111\u1ec3 s\u1eed d\u1ee5ng k\u1ef9 n\u0103ng", "C\u1eebu s\u00e1t s\u1ebd l\u00e0m t\u0103ng 2 \u0111i\u1ec3m hi\u1ebfu chi\u1ebfn. \u0110\u1ed3 s\u00e1t s\u1ebd l\u00e0m t\u0103ng 1 \u0111i\u1ec3m hi\u1ebfu chi\u1ebfn", "\u0110\u1ed1i v\u1edbi Ki\u1ebfm, Kunai, \u0110ao: N\u00ean t\u0103ng S\u1ee9c M\u1ea1nh, Th\u1ec3 L\u1ef1c, Th\u00e2n ph\u00e1p", "\u0110\u1ed1i v\u1edbi Cung, Phi Ti\u00eau, Qu\u1ea1t: N\u00ean t\u0103ng Chakra, Th\u1ec3 L\u1ef1c, Th\u00e2n ph\u00e1p", "L\u1eadp t\u1ed5 \u0111\u1ed9i \u0111i luy\u1ec7n c\u00f9ng nhau b\u1ea1n s\u1ebd nh\u1eadn \u0111\u01b0\u1ee3c nhi\u1ec1u kinh nghi\u1ec7m h\u01a1n v\u00e0 l\u00e0m nhi\u1ec7m v\u1ee5 nhanh h\u01a1n", "\u0110\u1ec3 gi\u1ea3m hi\u1ebfu chi\u1ebfn, b\u1ea1n ph\u1ea3i b\u1ecb ng\u01b0\u1eddi kh\u00e1c \u0111\u00e1nh tr\u1ecdng th\u01b0\u01a1ng. V\u00e0o \u0111\u1ea5u tr\u01b0\u1eddng \u0111\u1ec3 thi \u0111\u1ea5u \u0111\u1ec3 gi\u1ea3m", "Khi t\u00e1ch \u0111\u00e1 kh\u1ecfi trang b\u1ecb, b\u1ea1n s\u1ebd thu l\u1ea1i m\u1ed9t n\u1eeda s\u1ed1 \u0111\u00e1 \u00e9p v\u00e0o l\u00fac \u0111\u1ea7u", "B\u1ea1n c\u00f3 th\u1ec3 \u0111\u1ed5i Xu t\u1eeb Y\u00ean, v\u1edbi \u0111i\u1ec1u ki\u1ec7n c\u00f3 \u0111\u1ee7 \u0111i\u1ec3m ho\u1ea1t \u0111\u1ed9ng", "B\u1ea1n s\u1ebd c\u00f3 ph\u1ea7n th\u01b0\u1edfng n\u1ebfu \u0111\u1ea1t th\u00e0nh t\u00edch cao nh\u1ea5t trong \u0111\u1ea5u tr\u01b0\u1eddng m\u1ed7i ng\u00e0y", "\u0110\u1ec3 v\u00e0o khu v\u1ef1c \u0111\u1ea5u tr\u01b0\u1eddng, h\u00e3y t\u00ecm Rikudou \u0111\u1ee9ng \u1edf m\u1ed7i tr\u01b0\u1eddng", "B\u1ea1n c\u00f3 th\u1ec3 t\u0103ng t\u1ec9 l\u1ec7 th\u00e0nh c\u00f4ng khi n\u00e2ng c\u1ea5p \u0111\u1ed3 b\u1eb1ng c\u00e1ch ch\u1ecdn ph\u01b0\u01a1ng ph\u00e1p C\u1ea9n Th\u1eadn, nh\u01b0ng s\u1ebd t\u1ed1n L\u01b0\u1ee3ng", "B\u1ea1n \u0111\u01b0\u1ee3c t\u1eb7ng 10 l\u01b0\u1ee3ng khi \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 20 t\u1ea1i NPC Okanechan", "Ti\u1ec1n L\u01b0\u1ee3ng \u0111\u01b0\u1ee3c chia s\u1ebb cho 3 nh\u00e2n v\u1eadt trong 1 t\u00e0i kho\u1ea3n"};
            gameBE = "Quy \u0111\u1ecbnh";
            gameBG = "D\u1ee9a Nh\u1ecf..";
            gameBH = "Ch\u1edd";
            gameBI = "Menu";
            gameBJ = "C\u1ea7n";
            gameBK = "Di chuy\u1ec3n t\u1edbi";
            LANGUAGE = "Ng\u00f4n ng\u1eef";
            gameBM = "X\u00f3a b\u1ed9 nh\u1edb t\u1ea1m";
            LANGUAGES = new String[]{"Ti\u1ebfng vi\u1ec7t", "English"};
            var10000 = new String[]{"\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a", "\u1797\u17b6\u179f\u17b6\u17a2\u1784\u17cb\u1782\u17d2\u179b\u17c1\u179f"};
            gameBO = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t game \u0111\u1ec3 ch\u1ecdn l\u1ea1i ng\u00f4n ng\u1eef kh\u00f4ng ?";
            CLOSE = "\u0110\u00f3ng";
            gameBQ = "\u1ea8n";
            gameBR = "T\u1ef1 \u0111\u00e1nh";
            gameBS = "\u0110\u1ee9ng y\u00ean";
            gameBT = "do";
            gameBU = "Kh\u00f3a";
            gameBV = "M\u1edf kh\u00f3a";
            gameBW = "S\u1ed1 seri";
            gameBX = "M\u00e3 th\u1ebb";
            gameBY = "B\u1eadt";
            gameBZ = "T\u1eaft";
            gameCA = "M\u1edf link";
            gameCB = "N\u1ea1p";
            gameCC = "K\u00edch ho\u1ea1t";
            gameCD = "C\u1ea5u h\u00ecnh";
            DELETE = "X\u00f3a";
            gameCF = "Xem";
            gameCG = "Ti\u1ebfp t\u1ee5c";
            gameCH = "M\u00e3 r\u01b0\u01a1ng";
            gameCI = "Th\u1ebb c\u00e0o";
            gameCJ = "Ti\u1ebfp";
            gameCK = "S\u1eed d\u1ee5ng";
            gameCL = "S\u1eafp x\u1ebfp";
            gameCM = "B\u1ecf ra \u0111\u1ea5t";
            gameCN = "T\u00e1ch";
            gameCO = "Trang b\u1ecb \u0111\u00e3 \u0111\u01b0\u1ee3c t\u00e1ch, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c ";
            YES = "C\u00f3";
            gameCQ = "L\u1ea5y ra";
            gameCR = "B\u1ecf ra";
            gameCS = "R\u00fat xu";
            gameCT = "C\u1ea5t xu";
            gameCU = "Chuy\u1ec3n xu";
            gameCV = "C\u1ea5t v\u00e0o";
            gameCW = "B\u00e1n";
            gameCX = "B\u00e1n nhi\u1ec1u";
            gameCY = "B\u00e1n h\u1ebft";
            gameCZ = "Gi\u00e1";
            gameDA = "Mua";
            gameDB = "Mua nhi\u1ec1u";
            NO = "Kh\u00f4ng";
            EXIT = "Tho\u00e1t";
            CHAT = "Chat";
            OK = "OK";
            USERNAME = "T\u00e0i kho\u1ea3n";
            PASSWORD = "M\u1eadt kh\u1ea9u";
            REPASS = "Nh\u1eadp l\u1ea1i";
            gameDJ = "TK";
            gameDK = "MK";
            gameDL = "l\u1ea1i";
            RESTART = "Xin kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
            REPASSWORD = "Nh\u1eadp l\u1ea1i m\u1eadt kh\u1ea9u";
            REMEMBER = "Nh\u1edb";
            UNCHECK = "B\u1ecf";
            gameDQ = "\u0110\u0103ng k\u00fd";
            gameDR = "T\u0103ng \u0111\u1ed3 h\u1ecda (cho m\u00e1y m\u1ea1nh)";
            gameDS = "Gi\u1ea3m \u0111\u1ed3 h\u1ecda (cho m\u00e1y y\u1ebfu)";
            NOT_INPUT_USERNAME = "B\u1ea1n ch\u01b0a nh\u1eadp t\u00ean t\u00e0i kho\u1ea3n";
            NOT_SPEC_CHARACTER = "T\u00e0i kho\u1ea3n kh\u00f4ng \u0111\u01b0\u1ee3c c\u00f3 k\u00fd t\u1ef1 \u0111\u1eb7t bi\u1ec7t.";
            NOT_INPUT_PASS1 = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u l\u1ea7n m\u1ed9t.";
            NOT_INPUT_PASS2 = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u l\u1ea7n hai.";
            USERNAME_LENGHT = "T\u00ean t\u00e0i kho\u1ea3n ph\u1ea3i nhi\u1ec1u h\u01a1n 5 k\u00fd t\u1ef1";
            WRONG_PASSWORD = "M\u1eadt kh\u1ea9u kh\u00f4ng ch\u00ednh x\u00e1c.";
            REGISTER_TEXT = new String[]{"\u0110\u1ec3 x\u00e1c th\u1ef1c v\u1edbi t\u00ean", "b\u1ea1n ph\u1ea3i \u0111\u1ed3ng \u00fd v\u1edbi quy \u0111\u1ecbnh c\u1ee7a tr\u00f2 ch\u01a1i."};
            gameEA = "B\u1ea1n \u0111ang s\u1eed d\u1ee5ng m\u1ea1ng g\u00ec? (B\u1ea1n c\u00f3 th\u1ec3 ch\u1ecdn l\u1ea1i t\u1eeb Menu)";
            ASK_REG_NUM = "C\u00f3 ph\u1ea3i b\u1ea1n d\u00f9ng s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd kh\u00f4ng ?";
            gameEC = "tin nh\u1eafn ri\u00eang";
            gameED = new String[]{"Tin nh\u1eafn gia t\u1ed9c, nh\u00f3m", "Tin nh\u1eafn gia t\u1ed9c", "Tin nh\u1eafn nh\u00f3m"};
            gameEE = "h\u1ed9 t\u1ed1ng";
            gameEF = "C\u1ed9ng";
            gameEG = "C\u1ed9ng nhi\u1ec1u";
            gameEH = "\u0111i\u1ec3m ti\u1ec1m n\u0103ng";
            ACCEPT = "\u0110\u1ed3ng \u00fd";
            CANCEL = "H\u1ee7y";
            gameEK = "Danh s\u00e1ch";
            gameEL = "Th\u1eddi gian";
            gameEM = "Th\u00e0nh t\u00edch";
            gameEN = "T\u1ed1i \u0111a";
            gameEO = "T\u00edch l\u0169y";
            CONNECTING = "\u0110ang k\u1ebft n\u1ed1i";
            REGISTERING = "\u0110ang \u0111\u0103ng k\u00fd";
            LOGGING = "\u0110ang \u0111\u0103ng nh\u1eadp";
            gameES = "Ch\u01b0a ho\u00e0n th\u00e0nh";
            gameET = "Th\u1eddi gian ho\u00e0n th\u00e0nh";
            gameEU = "Tinh th\u1ea7n \u0111\u1ed3ng \u0111\u1ed9i";
            SELECT = "Ch\u1ecdn";
            gameEW = "B\u1ecf ch\u1ecdn";
            gameEX = "Ch\u1ecdn v\u1eadt ph\u1ea9m \u0111\u1ec3 xem th\u00f4ng tin.";
            gameEY = "G\u00e1n";
            gameEZ = "K\u1ebft qu\u1ea3";
            gameFA = "\u0110\u00e1nh gi\u00e1";
            gameFB = "C\u1ea5p";
            gameFC = "c\u1ea5p";
            gameFD = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t kh\u00f4ng?";
            gameFE = "Nh\u00e2n v\u1eadt c\u1ea7n \u0111\u1ed5i t\u00ean";
            gameFF = "M\u00e1y ch\u1ee7 n\u00e0y \u0111ang b\u1ea3o tr\u00ec ho\u1eb7c qu\u00e1 t\u1ea3i. Vui l\u00f2ng th\u1eed l\u1ea1i sau ho\u1eb7c ch\u1ecdn m\u00e1y ch\u1ee7 kh\u00e1c.";
            gameFG = "T\u1ea1o m\u1edbi";
            CHARNAME = "T\u00ean nh\u00e2n v\u1eadt";
            gameFI = "T\u00ean nh\u00e2n v\u1eadt mu\u1ed1n k\u1ebft b\u1ea1n";
            gameFJ = "\u0111\u00e3 tr\u1edf th\u00e0nh h\u1ea3o h\u1eefu.";
            gameFK = "\u0110ang t\u1ea3i... ";
            gameFL = "\u0110\u00f3ng";
            gameFM = "Nh\u1eadn th\u01b0\u1edfng";
            gameFN = "r\u01b0\u01a1ng hang \u0111\u1ed9ng";
            gameFO = "H\u00e0nh trang \u0111\u00e3 \u0111\u01b0\u1ee3c m\u1edf r\u1ed9ng";
            gameFP = "Kho\u1ea3ng c\u00e1ch h\u1ed9 t\u1ed1ng qu\u00e1 xa, nhi\u1ec7m v\u1ee5 \u0111\u00e3 th\u1ea5t b\u1ea1i";
            gameFQ = "Ng\u01b0\u1eddi \u0111\u01b0\u1ee3c h\u1ed9 t\u1ed1ng \u0111\u00e3 tr\u1ecdng th\u01b0\u01a1ng, nhi\u1ec7m v\u1ee5 \u0111\u00e3 th\u1ea5t b\u1ea1i";
            gameFR = "v\u0129nh vi\u1ec5n";
            gameFS = "Ch\u01b0a n\u00e2ng c\u1ea5p";
            gameFT = "Kh\u00f4ng th\u1ec3 n\u00e2ng c\u1ea5p";
            gameFU = "D\u00f9ng v\u1eadt ph\u1ea9m \u0111\u1eb7c bi\u1ec7t \u0111\u1ec3 n\u00e2ng c\u1ea5p";
            gameFV = "Luy\u1ec7n";
            gameFW = "Luy\u1ec7n \u0111\u00e1 th\u00e0nh c\u00f4ng, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            gameFX = new String[]{"Ch\u1ec9 \u0111\u01b0\u1ee3c chuy\u1ec3n h\u00f3a trang b\u1ecb c\u00f9ng", "lo\u1ea1i v\u00e0 c\u00f9ng c\u1ea5p tr\u1edf l\u00ean.", "S\u1ebd kh\u00f3a trang b\u1ecb sau khi chuy\u1ec3n h\u00f3a."};
            gameFY = "th\u1ea5t b\u1ea1i, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            gameFZ = "\u0110\u00e3 g\u1eedi tin nh\u1eafn, xin ch\u1edd tin nh\u1eafn x\u00e1c nh\u1eadn.";
            gameGA = "Kh\u00f4ng th\u1ec3 g\u1edfi tin nh\u1eafn. Xin ki\u1ec3m tra ti\u1ec1n v\u00e0 th\u1eed kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
            gameGB = "Xu \u0111ang g\u1eedi";
            gameGC = "B\u1eaft \u0111\u1ea7u";
            gameGD = "Ch\u1ecdn 2 vi\u00ean \u0111\u00e1 tr\u1edf l\u00ean";
            gameGE = "Ch\u1ecdn Trang B\u1ecb c\u1ea7n t\u00e1ch \u0110\u00e1";
            gameGF = "Ch\u1ecdn V\u1eadt Ph\u1ea9m v\u00e0 Xu trao \u0111\u1ed5i";
            gameGG = "Sang H\u00e0nh Trang \u0111\u1ec3 ch\u1ecdn";
            CHANGE = "\u0110\u1ed5i";
            gameGI = "\u00f4";
            gameGJ = "\u00f4 th\u1ee9";
            gameGK = new String[]{"Ph\u00edm Q", "Ph\u00edm W", "Ph\u00edm E"};
            gameGL = new String[]{"Ph\u00edm 7", "Ph\u00edm 8", "Ph\u00edm 9"};
            HAIR_STYLE = new String[][]{{"ng\u1eafn", "c\u00e0i tr\u00e2m", "b\u00fai", "x\u00f9"}, {"\u0111eo b\u0103ng", "b\u00f3 x\u00f9", "samurai", "nh\u00edm"}};
            gameGN = new String[]{"H\u00e0nh trang", "K\u1ef9 n\u0103ng", "Ti\u1ec1m n\u0103ng", "Th\u00f4ng tin", "Trang b\u1ecb", "Th\u00fa C\u01b0\u1ee1i"};
            gameGO = new String[]{"Ti\u1ec7m Y Ph\u1ee5c", "H\u00e0nh trang"};
            gameGP = new String[]{"N\u00f3n", "H\u00e0nh trang"};
            gameGQ = new String[]{"\u00c1o", "H\u00e0nh trang"};
            gameGR = new String[]{"G\u0103ng tay", "H\u00e0nh trang"};
            gameGS = new String[]{"Qu\u1ea7n", "H\u00e0nh trang"};
            gameGT = new String[]{"Gi\u00e0y", "H\u00e0nh trang"};
            gameGU = new String[]{"D\u00e2y chuy\u1ec1n", "H\u00e0nh trang"};
            gameGV = new String[]{"Nh\u1eabn", "H\u00e0nh trang"};
            gameGW = new String[]{"Ng\u1ecdc b\u1ed9i", "H\u00e0nh trang"};
            gameGX = new String[]{"B\u00f9a", "H\u00e0nh trang"};
            gameGY = new String[]{"Binh kh\u00ed", "H\u00e0nh trang"};
            gameGZ = new String[]{"D\u01b0\u1ee3c ph\u1ea9m", "H\u00e0nh trang"};
            gameHA = new String[]{"D\u01b0\u1ee3c ph\u1ea9m", "H\u00e0nh trang"};
            gameHB = new String[]{"Th\u1ee9c \u0103n", "H\u00e0nh trang"};
            gameHC = new String[]{"Th\u1ee9c \u0103n", "H\u00e0nh trang"};
            gameHD = new String[]{"N\u00e2ng c\u1ea5p", "H\u00e0nh trang"};
            gameHE = new String[]{"Gian h\u00e0ng", "H\u00e0nh trang"};
            gameHF = new String[]{"Chuy\u1ec3n h\u00f3a", "H\u00e0nh trang"};
            gameHG = new String[]{"Luy\u1ec7n \u0111\u00e1", "H\u00e0nh trang"};
            gameHH = new String[]{"R\u01b0\u01a1ng \u0111\u1ed3", "H\u00e0nh trang"};
            gameHI = new String[]{"C\u1eeda h\u00e0ng", "Qu\u1ea7y s\u00e1ch", "Th\u1eddi trang", "Gia T\u1ed9c"};
            gameHJ = new String[]{"B\u1ea3o v\u1eadt"};
            gameHK = new String[]{"T\u00e1ch \u0110\u00e1", "H\u00e0nh trang"};
            gameHL = new String[]{"Giao d\u1ecbch", "H\u00e0nh trang"};
            gameHM = new String[]{"Luy\u1ec7n th\u1ea1ch", "H\u00e0nh trang"};
            gameHN = new String[]{"D\u1ecbch chuy\u1ec3n", "H\u00e0nh trang"};
            gameHO = new String[]{"Tinh luy\u1ec7n", "H\u00e0nh trang"};
            gameHP = new String[]{"Kh\u1ea3m ng\u1ecdc", "H\u00e0nh trang"};
            gameHQ = new String[]{"Luy\u1ec7n ng\u1ecdc", "H\u00e0nh trang"};
            gameHS = new String[]{"G\u1ecdt ng\u1ecdc", "H\u00e0nh trang"};
            gameHR = new String[]{"Giao \u0111\u1ed3", "H\u00e0nh trang"};
            gameHT = new String[]{"Th\u00e1o ng\u1ecdc", "H\u00e0nh trang"};
            gameXN = new String[]{"Nh\u1eb7t \u0111\u1ed3", "H\u00e0nh trang"};
            var10000 = new String[]{"Del \u0111\u1ed3", "H\u00e0nh trang"};
            gameXO = "X\u00f3a";
            gameXP = "Th\u00eam";
            gameAU = "Ta s\u1ebd l\u00e0m gi\u1ea3m \u0111i ch\u1ec9 s\u1ed1 b\u1ea5t l\u1ee3i tr\u00ean vi\u00ean ng\u1ecdc n\u00e0y.";
            gameAV = "Ta s\u1ebd gi\u00fap ng\u01b0\u01a1i th\u00e1o b\u1ecf ng\u1ecdc kh\u1ea3m tr\u00ean trang b\u1ecb.";
            gameHU = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- Qua trang H\u00e0nh Trang \u0111\u1ec3 ch\u1ecdn \u0110\u00e1", "- S\u1ed1 l\u01b0\u1ee3ng \u0111\u00e1 t\u1eeb 2 \u0111\u1ebfn 24"};
            gameHV = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- N\u00e2ng c\u1ea5p c\u1ea9n th\u1eadn c\u1ea7n d\u00f9ng l\u01b0\u1ee3ng", "- Ch\u1ec9 ch\u1ecdn Trang B\u1ecb v\u00e0 \u0110\u00e1", "Trang b\u1ecb \u0111\u00e3 \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p t\u1ed1i \u0111a"};
            gameHW = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- Ch\u1ec9 ch\u1ecdn Trang B\u1ecb v\u00e0 Ng\u1ecdc"};
            gameHX = "Kh\u00f3a G.D\u1ecbch";
            gameHY = "- Luy\u1ec7n th\u00e0nh \u0110\u00e1 c\u1ea5p";
            gameHZ = "- C\u1ea7n: # y\u00ean";
            gameKA = "- C\u1ea7n: # l\u01b0\u1ee3ng";
            gameKB = "- C\u1ea7n: # xu";
            gameKC = "- X\u00e1c xu\u1ea5t th\u00e0nh c\u00f4ng";
            gameKD = "(th\u00e0nh c\u00f4ng ";
            gameKE = "C\u1ed9ng";
            gameKG = "\u0110\u00e3 kh\u00f3a";
            gameKH = "Ti\u00eau di\u1ec7t";
            gameKI = "B\u1eaft t\u00e0 th\u00fa";
            gameKJ = "Ti\u00eau di\u1ec7t tinh anh";
            gameKK = "Ti\u00eau di\u1ec7t th\u1ee7 l\u0129nh";
            gameKL = "H\u1ed9 t\u1ed1ng tr\u1ebb l\u1ea1c";
            gameKM = "Kh\u00f4ng kh\u00f3a";
            gameKN = "H\u1ea1n s\u1eed d\u1ee5ng";
            gameKO = "Gi\u00e1 b\u00e1n: # y\u00ean";
            gameKP = "Gi\u00e1 mua: # xu";
            gameKQ = "Gi\u00e1 mua: # xu gia t\u1ed9c";
            gameKR = "Gi\u00e1 mua: # y\u00ean";
            gameKS = "Gi\u00e1 mua: # l\u01b0\u1ee3ng";
            gameKT = "l\u01b0\u1ee3ng";
            gameKU = "Ch\u01b0a c\u00f3";
            gameKV = "C\u1ea5p k\u1ebf: c\u1ea5p #";
            gameKW = "C\u1ea5p hi\u1ec7n t\u1ea1i: c\u1ea5p #";
            gameKX = "C\u1ea5p t\u1ed1i \u0111a";
            gameKY = "\u0110\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a";
            gameKZ = "Y\u00eau c\u1ea7u: tr\u00ecnh \u0111\u1ed9 c\u1ea5p";
            gameMA = "L\u1edbp: ";
            gameMB = new String[]{"Ch\u00ednh tuy\u1ebfn", "Ph\u1ee5 tuy\u1ebfn"};
            ME_TASK = "Nhi\u1ec7m v\u1ee5";
            gameMD = "Nh\u1eadn NV \u1edf";
            gameME = "B\u1ea1ch gi\u1ea3";
            gameMF = "H\u1eafc gi\u1ea3";
            gameMG = "Trung l\u1eadp";
            gameMH = "Nh\u00f3m";
            gameMI = "T\u00ecm Nh\u00f3m";
            gameMJ = "\u0110i\u1ec3m hi\u1ebfu chi\u1ebfn c\u1ee7a b\u1ea1n hi\u1ec7n t\u1ea1i l\u00e0 ";
            gameMK = new String[]{"B\u1ea1n b\u00e8", "Th\u00f9 \u0110\u1ecbch"};
            gameML = "B\u1ea1n ch\u01b0a k\u1ebft b\u1ea1n v\u1edbi ai";
            gameMM = "ch\u1edd x\u00e1c nh\u1eadn";
            gameMN = "\u0111\u00e3 th\u00eam b\u1ea1n v\u00e0o danh s\u00e1ch b\u1ea1n b\u00e8";
            gameMO = "B\u1ea1n \u0111\u00e3 th\u00eam";
            gameMP = "v\u00e0o danh s\u00e1ch";
            gameMQ = "B\u1ea1n v\u00e0";
            gameMR = new String[]{"C\u1eeda h\u00e0ng", "B\u1ea3n th\u00e2n", "B\u1ea3n \u0111\u1ed3", "T\u1ed5ng h\u1ee3p", "Tho\u00e1t", "Trang s\u1ee9c", "T\u00ednh n\u0103ng", "D\u01b0\u1ee3c kh\u00f3a", "D\u01b0\u1ee3c ph\u1ea9m", "T\u1ea1p h\u00f3a kh\u00f3a", "T\u1ea1p h\u00f3a", "C\u01b0\u1eddng h\u00f3a", "Luy\u1ec7n h\u00f3a", "Luy\u1ec7n h\u00f3a kh\u00f3a", "Th\u1ee7 kh\u1ed1", "T\u00e1ch trang b\u1ecb", "Khu v\u1ef1c", "Giao d\u1ecbch", "Tin nh\u1eafn", "Ch\u1ecdn Nh\u00e2n v\u1eadt"};
            gameMS = new String[]{"H\u1ed7 tr\u1ee3 b\u1ecb \u0111\u1ed9ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng"};
            gameMT = new String[]{"Nh\u00e2n v\u1eadt: ", "Hi\u1ebfu chi\u1ebfn: ", "Tr\u00ecnh \u0111\u1ed9: ", "L\u1edbp: ", "", "HP: ", "MP: ", "T\u1ed1c \u0111\u1ed9: ", "T\u1ea5n c\u00f4ng: ", "H\u1ecfa ch\u1ed1ng: ", "B\u0103ng ch\u1ed1ng: ", "Phong ch\u1ed1ng: ", "Gi\u1ea3m s\u00e1t th\u01b0\u01a1ng: ", "\u0110\u1ed9 ch\u00ednh x\u00e1c: ", "Kh\u1ea3 n\u0103ng n\u00e9 \u0111\u00f2n: ", "Ch\u00ed m\u1ea1ng: ", "Ph\u1ea3n \u0111\u00f2n c\u1eadn chi\u1ebfn: ", "C\u01b0\u1eddng kh\u1eafc: ", "H\u1ea1 kh\u1eafc: ", "\u0110i\u1ec3m ho\u1ea1t \u0111\u1ed9ng: "};
            gameMU = " l\u1ea7n";
            gameMV = new String[]{"H\u1ecdc Gi\u1ea3", "H\u1ea1 nh\u1eabn", "Trung Nh\u1eabn", "Th\u01b0\u1ee3ng Nh\u1eabn", "Nh\u1eabn Gi\u1ea3"};
            gameMW = new String[]{"\u0110i\u1ec3m ho\u1ea1t \u0111\u1ed9ng: ", "Danh v\u1ecdng v\u0169 kh\u00ed: ", "Danh v\u1ecdng d\u00e2y chuy\u1ec1n: ", "Danh v\u1ecdng nh\u1eabn: ", "Danh v\u1ecdng ng\u1ecdc b\u1ed9i: ", "Danh v\u1ecdng b\u00f9a: ", "Danh v\u1ecdng n\u00f3n: ", "Danh v\u1ecdng \u00e1o: ", "Danh v\u1ecdng g\u0103ng tay: ", "Danh v\u1ecdng qu\u1ea7n: ", "Danh v\u1ecdng gi\u00e0y: ", "Ho\u00e0n th\u00e0nh NV m\u1ed7i ng\u00e0y: ", "Truy b\u1eaft T\u00e0 Th\u00fa c\u00f2n: ", "H\u1ecdc s\u00e1ch ti\u1ec1m n\u0103ng s\u01a1: ", "H\u1ecdc s\u00e1ch k\u1ef9 n\u0103ng s\u01a1: ", "Gia t\u1ed9c: ", "V\u00e0o hang \u0111\u1ed9ng c\u00f2n: ", "\u0110i\u1ec3m tinh t\u00fa: ", "S\u1ed1 l\u1ea7n \u0103n b\u00e1nh phong l\u00f4i: ", "S\u1ed1 l\u1ea7n \u0103n b\u00e1nh b\u0103ng h\u1ecfa: "};
            gameMX = new String[]{"T\u00ean: ", "Gi\u1edbi t\u00ednh: ", "T\u00f3c: "};
            MENUGENDER = new String[]{"N\u1eef", "Nam"};
            gameMZ = new String[]{"S\u1ee9c m\u1ea1nh", "Th\u00e2n ph\u00e1p", "Th\u1ec3 l\u1ef1c", "Chakra"};
            gameNA = "Ch\u01b0a c\u00f3 ai c\u1eebu s\u00e1t b\u1ea1n";
            gameNB = "B\u1ea1n \u0111\u00e3 th\u1eafng #.";
            gameNC = "B\u1ea1n \u0111\u00e3 thua #.";
            gameND = "Cu\u1ed9c so t\u00e0i gi\u1eefa b\u1ea1n v\u00e0 # \u0111\u00e3 k\u1ebft th\u00fac";
            gameNE = new String[]{"", "Tinh Anh", "Th\u1ee7 L\u0129nh", "T\u00e0 Th\u00fa"};
            gameNF = " b\u1eaft \u0111\u1ea7u c\u1eebu s\u00e1t b\u1ea1n";
            gameNG = "\u0110i\u1ec3m ti\u1ec1m n\u0103ng";
            gameNH = "\u0110i\u1ec3m k\u1ef9 n\u0103ng";
            gameNI = "Kh\u00f4ng \u0111\u1ee7 MP \u0111\u1ec3 s\u1eed d\u1ee5ng";
            gameNJ = "Ch\u1ec9 \u0111\u01b0\u1ee3c v\u1eadt ph\u1ea9m kh\u00f4ng kh\u00f3a";
            gameNK = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn v\u1eadt ph\u1ea9m kh\u00f4ng kh\u00f3a v\u00e0 kh\u00f4ng c\u00f3 h\u1ea1n s\u1eed d\u1ee5ng";
            gameNL = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1 \u0111\u1ec3 luy\u1ec7n c\u1ea5p";
            gameNM = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1, Trang b\u1ecb, v\u00e0 B\u1ea3o hi\u1ec3m \u0111\u1ec3 n\u00e2ng c\u1ea5p";
            gameNN = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn Trang b\u1ecb v\u00e0 v\u1eadt ph\u1ea9m Ho\u00e1n chuy\u1ec3n.";
            gameNO = "Trang b\u1ecb kh\u00f4ng th\u1ec3 n\u00e2ng c\u1ea5p";
            gameNP = "Trang b\u1ecb \u0111\u00e3 n\u00e2ng c\u1ea5p t\u1ed1i \u0111a";
            gameNQ = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn trang b\u1ecb \u0111\u00e3 n\u00e2ng c\u1ea5p m\u1edbi c\u00f3 th\u1ec3 t\u00e1ch \u0111\u01b0\u1ee3c";
            gameNR = "V\u1eadt ph\u1ea9m giao d\u1ecbch \u0111\u00e3 \u0111\u1ea7y";
            gameNS = "S\u1ed1 l\u01b0\u1ee3ng \u0111\u00e3 \u0111\u1ea7y";
            gameNT = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 \u0111i\u1ec3m c\u1ed9ng";
            gameNU = "B\u1ea1n ch\u01b0a nh\u1eadp \u0111i\u1ec3m c\u1ed9ng";
            gameNV = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin lo\u1ea1i th\u1ebb";
            gameNW = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin m\u1ec7nh gi\u00e1.";
            gameNX = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin s\u1ed1 seri";
            gameNY = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin kho\u1ea3ng th\u1eddi gian n\u1ea1p.";
            gameNZ = "B\u1ea1n ch\u01b0a nh\u1eadp v\u00e0o t\u00ean c\u1ea7n th\u00eam";
            gamePA = "Nh\u1eadp \u0111i\u1ec3m";
            gamePB = "Nh\u1eadp Xu";
            gamePC = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng";
            INPUT_NICK = "T\u00ean t\u00e0i kho\u1ea3n";
            gamePE = "Xu";
            gamePF = "Y\u00ean";
            gamePG = "L\u01b0\u1ee3ng";
            gamePH = "C\u1ea5t v\u00e0o h\u00e0nh trang";
            gamePI = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n b\u00e3i nhi\u1ec7m ch\u1ee9c v\u1ee5 c\u1ee7a ng\u01b0\u1eddi n\u00e0y kh\u00f4ng?";
            gamePJ = "Tr\u1ee5c xu\u1ea5t th\u00e0nh vi\u00ean s\u1ebd b\u1ecb gi\u1ea3m ng\u00e2n s\u00e1ch gia t\u1ed9c (xem chi ti\u1ebft t\u1ea1i Npc Kanata). B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n tr\u1ee5c xu\u1ea5t ng\u01b0\u1eddi n\u00e0y kh\u00f4ng?";
            gamePK = "T\u1ef1 r\u1eddi kh\u1ecfi gia t\u1ed9c s\u1ebd b\u1ecb gi\u1ea3m xu trong h\u00e0nh trang (xem chi ti\u1ebft t\u1ea1i Npc Kanata). B\u1ea1n c\u00f3 mu\u1ed1n r\u1eddi kh\u1ecfi kh\u00f4ng?";
            gamePL = "Sau khi s\u1eed d\u1ee5ng v\u1eadt ph\u1ea9m s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n s\u1eed d\u1ee5ng kh\u00f4ng?";
            gamePM = "Sau khi b\u00e1n v\u1eadt ph\u1ea9m s\u1ebd kh\u00f4ng th\u1ec3 ph\u1ee5c h\u1ed3i. B\u1ea1n c\u00f3 mu\u1ed1n b\u00e1n v\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng?";
            gamePN = new String[][]{{"n\u00f3n"}, {"v\u0169", "kh\u00ed"}, {"\u00e1o"}, {"v\u00f2ng", "c\u1ed5"}, {"g\u0103ng", "tay"}, {"nh\u1eabn"}, {"qu\u1ea7n"}, {"b\u1ed9i"}, {"gi\u00e0y"}, {"b\u00f9a"}, {"th\u00fa", "nu\u00f4i"}, {"m\u1eb7t", "n\u1ea1"}, {"ninja", "yoroi"}, {"gia", "t\u1ed9c"}, {"ch\u01b0a", "m\u1edf"}, {"b\u00ed", "k\u00edp"}, {"\u00e1o", "gi\u00e1p"}, {"y\u00ean", ""}, {"c\u01b0\u01a1ng", ""}, {"trang", "s\u1ee9c"}, {"\u0111\u1ed9ng", "c\u01a1"}, {"\u0111\u1ecbnh", "v\u1ecb"}, {"b\u1ed9", "\u0111k"}, {"b\u00ecnh", "nitro"}};
            gamePO = new String[]{"Ch\u01b0a v\u00e0o tr\u01b0\u1eddng", "Tr\u01b0\u1eddng: Hirosaki", "Tr\u01b0\u1eddng: Ookaza", "Tr\u01b0\u1eddng: Haruna"};
            gamePP = new String[]{"", "Thu\u1ed9c t\u00ednh: H\u1ecfa", "Thu\u1ed9c t\u00ednh: Th\u1ee7y", "Thu\u1ed9c t\u00ednh: Phong", "", "", ""};
            gamePQ = "B\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            gamePR = "B\u1ea1n ch\u01b0a nh\u1eadp v\u00e0o s\u1ed1 l\u01b0\u01a1ng";
            gamePS = "Kh\u00f4ng th\u1ec3 b\u00e1n trang b\u1ecb \u0111\u00e3 n\u00e2ng c\u1ea5p";
            gamePT = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 chuy\u1ec3n.";
            gamePU = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 c\u1ea5t";
            gamePV = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 r\u00fat";
            gamePW = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 s\u1ed1 l\u01b0\u1ee3ng \u0111\u1ec3 b\u00e1n";
            gamePX = new String[]{"Th\u00e0nh c\u00f4ng, trang b\u1ecb \u0111\u01b0\u1ee3c l\u00ean c\u1ea5p ", "Th\u1ea5t b\u1ea1i, trang b\u1ecb tr\u1edf v\u1ec1 c\u1ea5p ", "Trang b\u1ecb \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p t\u1ed1i \u0111a", "Trang b\u1ecb c\u1ea5p"};
            gamePY = new String[]{"Kh\u1ea3m ng\u1ecdc th\u00e0nh c\u00f4ng", "Kh\u1ea3m ng\u1ecdc th\u1ea5t b\u1ea1i"};
            MONTH = "th\u00e1ng";
            WEEK = "tu\u1ea7n";
            DAY = "ng\u00e0y";
            HOUR = "gi\u1edd";
            gameQD = "gi\u00e2y";
            MINUTE = "ph\u00fat";
            gameQF = "\u1ea2nh h\u01b0\u1edfng";
            gameQG = "Ph\u1ea1m vi";
            gameQH = "MP m\u1ea5t";
            gameQI = "Kho\u1ea3ng c\u00e1ch thi tri\u1ec3n";
            gameQJ = "Ph\u1ea3i c\u00f3 t\u1eeb 2 vi\u00ean \u0111\u00e1 tr\u1edf l\u00ean m\u1edbi c\u00f3 th\u1ec3 luy\u1ec7n \u0111\u01b0\u1ee3c";
            gameQK = "Gi\u1edbi t\u00ednh kh\u00f4ng ph\u00f9 h\u1ee3p";
            gameQL = "Kh\u00f4ng c\u00f3 ng\u01b0\u1eddi ch\u01a1i kh\u00e1c";
            gameQM = "Tr\u00ecnh \u0111\u1ed9 c\u1ee7a b\u1ea1n ch\u01b0a \u0111\u1ea1t y\u00eau c\u1ea7u";
            gameQN = "\u0110\u00e1 \u0111\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a";
            gameQO = "\u0110\u00e1 sau khi luy\u1ec7n c\u1ea5p s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp t\u1ee5c kh\u00f4ng?";
            gameQP = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 luy\u1ec7n \u0111\u00e1";
            gameQQ = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 l\u01b0\u1ee3ng \u0111\u1ec3 n\u00e2ng c\u1ea5p trang b\u1ecb";
            gameQR = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu ho\u1eb7c y\u00ean \u0111\u1ec3 n\u00e2ng c\u1ea5p trang b\u1ecb";
            gameQS = "Nhi\u1ec1u \u0111\u00e1 qu\u00e1 s\u1ebd b\u1ecb l\u00e3ng ph\u00ed. B\u1ea1n c\u00f3 ch\u1eafc ch\u1eafn mu\u1ed1n n\u00e2ng c\u1ea5p?";
            gameQT = "Sau khi n\u00e2ng c\u1ea5p trang b\u1ecb s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp t\u1ee5c kh\u00f4ng?";
            gameQU = "Kh\u00f4ng th\u1ec3 t\u00e1ch trang b\u1ecb ch\u01b0a n\u00e2ng c\u1ea5p";
            gameQV = "H\u00e0nh trang kh\u00f4ng \u0111\u1ee7 ch\u1ed7 tr\u1ed1ng";
            gameQW = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n t\u00e1ch kh\u00f4ng?";
            gameQX = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n chuy\u1ec3n h\u00f3a kh\u00f4ng?";
            gameQY = "m\u1eddi b\u1ea1n giao d\u1ecbch. B\u1ea1n c\u00f3 mu\u1ed1n giao d\u1ecbch kh\u00f4ng?";
            gameQZ = "m\u1eddi b\u1ea1n v\u00e0o t\u1ed9c. B\u1ea1n c\u00f3 mu\u1ed1n l\u00e0 th\u00e0nh vi\u00ean c\u1ee7a gia t\u1ed9c '#' kh\u00f4ng?";
            gameRA = "mu\u1ed1n xin v\u00e0o gia t\u1ed9c. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            gameRB = "mu\u1ed1n t\u1ef7 th\u00ed v\u1edbi b\u1ea1n. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            gameRD = "m\u1eddi b\u1ea1n v\u00e0o nh\u00f3m. B\u1ea1n c\u00f3 mu\u1ed1n v\u00e0o kh\u00f4ng?";
            gameRE = "mu\u1ed1n xin v\u00e0o nh\u00f3m. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            gameRF = "Chuy\u1ec3n h\u00f3a trang b\u1ecb th\u00e0nh c\u00f4ng.";
            gameRG = new String[]{"Gi\u1edbi t\u00ednh: n\u1eef", "Gi\u1edbi t\u00ednh: nam"};
            gameRH = "Khu v\u1ef1c";
            gameRI = "D\u00e2n s\u1ed1";
            gameRJ = "Nh\u00f3m";
            gameRK = "Hi\u1ec7n t\u1ea1i b\u1ea1n kh\u00f4ng v\u00e0o nh\u00f3m n\u00e0o";
            gameRL = "l\u1ea7n";
            gameRM = new String[]{"Th\u00f4ng tin", "Th\u00e0nh vi\u00ean", "Nh\u00e0 Kho", "Th\u1ed1ng K\u00ea", "Th\u1ea7n Th\u00fa"};
            gameRN = new String[]{"Gia t\u1ed9c: ", "T\u1ed9c tr\u01b0\u1edfng: ", "Th\u00e0nh vi\u00ean: ", "C\u1ea5p: ", "Kinh nghi\u1ec7m: ", "Ng\u00e2n s\u00e1ch: ", "Th\u00e0nh l\u1eadp: ", "C\u1ed1ng hi\u1ebfn: ", "Ph\u00ed duy tr\u00ec: ", "Ph\u00ed n\u00e2ng c\u1ea5p: ", "V\u00e0o L\u00e3nh \u0110\u1ecba Gia T\u1ed9c: c\u00f2n ", "C\u1ed1ng hi\u1ebfn tu\u1ea7n: ", "S\u1eed d\u1ee5ng l\u1ec7nh b\u00e0i c\u00f2n: "};
            CLAN_ACTIVITY = new String[]{"xu l\u00fac", "Th\u00e0nh l\u1eadp gia t\u1ed9c, ng\u00e2n s\u00e1ch nh\u1eadn", "b\u1ecb tr\u1ee5c xu\u1ea5t, ng\u00e2n s\u00e1ch tr\u1eeb", "\u0111\u00f3ng g\u00f3p qu\u1ef9 gia t\u1ed9c, ng\u00e2n s\u00e1ch t\u0103ng", "r\u00fat qu\u1ef9 gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m", "Thu ph\u00ed duy tr\u00ec gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m", "n\u00e2ng c\u1ea5p gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m"};
            gameRP = "Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a gia nh\u1eadp gia t\u1ed9c";
            gameRQ = "Ph\u00e1t cho Th\u00e0nh vi\u00ean";
            gameRR = new String[][]{{"Tr\u01b0\u1eddng Hirosaki"}, {"Tr\u01b0\u1eddng Haruna"}, {"Tr\u01b0\u1eddng Ookaza"}, {"L\u00e0ng", "L\u00e0ng Kojin", "L\u00e0ng Sanzu", "L\u00e0ng Tone", "L\u00e0ng ch\u00e0i", "L\u00e0ng Chakumi", "L\u00e0ng Echigo", "L\u00e0ng Oshin"}, {"Khu v\u1ef1c"}};
            gameRS = new String[]{"N\u00f3n", "Nh\u00e2n", "\u00c1o", "D\u00e2y chuy\u1ec1n", "G\u0103ng tay", "Nh\u1eabn", "Qu\u1ea7n", "Ng\u1ecdc b\u1ed9i", "Gi\u00e0y", "B\u00f9a"};
            gameRT = new String[]{"K\u00edch \u1ea9n", "K\u00edch c\u1ea5p \u0111\u1ed9"};
            gameRU = new String[]{"", "H\u1ecfa", "Th\u1ee7y", "Phong"};
            CHARINGFO = new String[]{"Nh\u00e2n v\u1eadt", "Level", ""};
            gameRW = "V\u00f4 chi\u00eau th\u1eafng h\u1eefu chi\u00eau. Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a c\u00f3 chi\u00eau \u0111\u1ec3 \u0111\u00e1nh.";
            gameRX = "B\u1ea1n ch\u01b0a c\u00f3 v\u0169 kh\u00ed. Xin v\u00e0o Menu/B\u1ea3n Th\u00e2n/Trang b\u1ecb \u0111\u1ec3 ki\u1ec3m tra";
            gameRY = "V\u1eadt ph\u1ea9m \u0111\u00e3 b\u1ecb kh\u00f3a";
            gameRZ = "V\u1eadt ph\u1ea9m, trang b\u1ecb v\u00e0 \u0111\u00e1";
            gameSA = "M\u1ee9c gi\u00e1 (xu)";
            gameSB = "M\u1ee9c gi\u00e1 (y\u00ean)";
            gameSC = "\u0110\u00e3 h\u1ebft hi\u1ec7u qu\u1ea3 th\u1ee9c \u0103n";
            gameSD = "Level c\u1ee7a b\u1ea1n kh\u00f4ng \u0111\u1ee7 \u0111\u1ec3 s\u1eed d\u1ee5ng";
            gameSE = "\u0110\u00e3 h\u1ebft b\u00ecnh MP";
            gameSF = "\u0110\u00e3 h\u1ebft b\u00ecnh HP";
            gameSG = new String[]{"Giao d\u1ecbch", "T\u1ef7 th\u00ed", "C\u1eebu s\u00e1t", "K\u1ebft b\u1ea1n", "M\u1eddi v\u00e0o nh\u00f3m", "Ph\u1ee5c h\u1ed3i", "Xem th\u00f4ng tin", "Chat ri\u00eang", "M\u1eddi v\u00e0o t\u1ed9c", "Xin v\u00e0o t\u1ed9c", "Ch\u1eb7n xin v\u00e0o t\u1ed9c", "T\u1ef1 H\u1ed3i Sinh", "C\u1ea5m Chat"};
            gameSH = "B\u1ea1n \u0111ang \u1edf khu v\u1ef1c n\u00e0y";
            gameSI = new String[]{"H\u00e3y \u0111i t\u00ecm ", " \u1edf ", " \u0111\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5.", "B\u1ea1n \u0111\u00e3 ho\u00e0n th\u00e0nh h\u1ebft nhi\u1ec7m v\u1ee5 phi\u00ean b\u1ea3n n\u00e0y, vui l\u00f2ng ch\u1edd cho \u0111\u1ebfn khi ra phi\u00ean b\u1ea3n ti\u1ebfp theo."};
            gameSJ = new String[]{"Ki\u1ec7t s\u1ee9c", "\u0110\u1ee9ng nh\u00ecn", "Quay v\u1ec1", "H\u1ed3i sinh t\u1ea1i ch\u1ed7 (1 l\u01b0\u1ee3ng)"};
            gameSK = "Sau khi gia nh\u1eadp v\u00e0o l\u1edbp h\u1ecdc, th\u00ec c\u00f3 th\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5 t\u1eeb hi\u1ec7u tr\u01b0\u1edfng";
            gameSL = "T\u1ea1o nh\u00f3m";
            gameSM = "R\u1eddi nh\u00f3m";
            gameSN = "Nh\u00f3m tr\u01b0\u1edfng";
            gameSO = "Kh\u00f3a nh\u00f3m";
            gameSP = "M\u1edf nh\u00f3m";
            gameSQ = "Xin gia nh\u1eadp";
            gameSR = "T\u00ecm l\u1ea1i";
            gameSS = "Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a c\u00f3 nh\u00f3m";
            gameST = "Ch\u01b0a c\u00f3 th\u00f4ng tin";
            gameSU = "Hi\u1ec7n t\u1ea1i kh\u00f4ng t\u00ecm th\u1ea5y nh\u00f3m";
            gameSV = new String[]{"PK Th\u01b0\u1eddng", "PK Phe", "PK Bang", "PK \u0110\u1ed3 S\u00e1t"};
            gameSW = new String[]{"Tr\u1ea1ng th\u00e1i PK", "B\u1ea1n b\u00e8", "Th\u00f9 \u0110\u1ecbch", "Nh\u00f3m", "T\u00ecm nh\u00f3m", "Gia t\u1ed9c", "B\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n", "T\u1ef1 \u0111\u1ed9ng", "B\u00e1n Shinwa", "Luy\u1ec7n th\u1ea1ch", "Tinh luy\u1ec7n", "D\u1ecbch chuy\u1ec3n"};
            gameSX = new String[]{"B\u1ea3n \u0111\u1ed3", "Nhi\u1ec7m v\u1ee5", "Gia t\u1ed9c"};
            gameSY = new String[]{"T\u1ed9c tr\u01b0\u1edfng", "T\u1ed9c ph\u00f3", "Tr\u01b0\u1edfng l\u00e3o", "\u01afu t\u00fa", "Th\u00e0nh vi\u00ean"};
            gameSZ = new String[]{"(TT)", "(TP)", "(TL)", "(UT)"};
            gameTA = new String[]{"Ch\u1ec9 hi\u1ec7n Online", "R\u1eddi kh\u1ecfi", "Th\u00f4ng b\u00e1o", "\u0110\u00f3ng g\u00f3p", "R\u00fat qu\u1ef9", "N\u00e2ng C\u1ea5p", "M\u1eddi v\u00e0o l\u00e3nh \u0111\u1ecba", "M\u1eddi v\u00e0o Gia t\u1ed9c chi\u1ebfn", "Khai m\u1edf"};
            gameTB = "SX theo C.Hi\u1ebfn tu\u1ea7n";
            gameTC = new String[]{"Tr\u1ee5c xu\u1ea5t", "Nh\u01b0\u1eddng", "K\u1ebft b\u1ea1n"};
            gameTD = " \u0111\u01b0\u1ee3c l\u00ean l\u00e0m nh\u00f3m tr\u01b0\u1edfng.";
            gameTE = "B\u1ea1n b\u1ecb \u0111u\u1ed5i ra kh\u1ecfi nh\u00f3m";
            gameTF = "M\u1eddi v\u00e0o nh\u00f3m";
            gameTG = "Th\u00eam";
            gameTH = "V\u0169 kh\u00ed kh\u00f4ng th\u00edch h\u1ee3p.";
            gameTI = "B\u1ea1n c\u00f3 mu\u1ed1n x\u00f3a ng\u01b0\u1eddi n\u00e0y ra kh\u1ecfi danh s\u00e1ch?";
            gameTJ = new String[]{"B\u1ea1n ph\u1ea3i v\u00e0o tr\u01b0\u1eddng \u0111\u1ec3 t\u0103ng \u0111i\u1ec3m"};
            gameTK = new String[]{"S\u1ee9c m\u1ea1nh = T\u1ea5n c\u00f4ng", "Th\u00e2n ph\u00e1p = n\u00e9,ch\u00ednh x\u00e1c", "Th\u1ec3 l\u1ef1c = HP", "Chakra = MP"};
            gameTL = new String[]{"Kh\u00f4ng c\u1ea7n t\u0103ng s\u1ee9c m\u1ea1nh", "Th\u00e2n ph\u00e1p = n\u00e9,ch\u00ednh x\u00e1c", "Th\u1ec3 l\u1ef1c = HP", "Chakra = T\u1ea5n c\u00f4ng, MP"};
            CLOSE_CURTAB = "\u0110\u00f3ng tab hi\u1ec7n t\u1ea1i";
            PUBLICCHAT = new String[]{"C\u00f4ng c\u1ed9ng", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi \u0111\u1ee9ng g\u1ea7n t\u1ea1i \u0111\u00e2y"};
            PARTYCHAT = new String[]{"Chung nh\u00f3m", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi trong c\u00f9ng nh\u00f3m t\u1ea1i \u0111\u00e2y"};
            GLOBALCHAT = new String[]{"K\u00eanh th\u1ebf gi\u1edbi", "B\u1ea1n m\u1ea5t 5 l\u01b0\u1ee3ng m\u1ed7i l\u1ea7n chat k\u00eanh th\u1ebf gi\u1edbi.", "T\u1ea5t c\u1ea3 ng\u01b0\u1eddi \u0111ang online \u0111\u1ec1u th\u1ea5y b\u1ea1n chat.", "B\u1ea1n s\u1ebd b\u1ecb kh\u00f3a t\u00e0i kho\u1ea3n n\u1ebfu ch\u1eedi b\u1eady, qu\u1ea3ng c\u00e1o wap web tr\u00ean k\u00eanh th\u1ebf gi\u1edbi."};
            CLANCHAT = new String[]{"Gia t\u1ed9c", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi trong gia t\u1ed9c t\u1ea1i \u0111\u00e2y"};
            gameTR = "Ch\u1eb7n k\u00eanh th\u1ebf gi\u1edbi: ";
            gameTS = "Ch\u1eb7n chat ri\u00eang: ";
            gameTT = "B\u1ed5 nhi\u1ec7m";
            gameTU = "B\u00e3i nhi\u1ec7m";
            gameTV = "Tr\u1ee5c xu\u1ea5t";
            gameTW = "M\u1eadt kh\u1ea9u ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i l\u00e0 6 k\u00fd t\u1ef1.";
            gameTX = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u1ec9 cho nh\u1eadp s\u1ed1.";
            gameTY = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 kh\u00f4ng \u0111\u01b0\u1ee3c ch\u1ee9a s\u1ed1 0 \u1edf \u0111\u1ea7u.";
            gameTZ = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u01b0a \u0111\u00fang.";
            gameUA = "\u0110\u1ec3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng n\u00e0y b\u1ea1n ph\u1ea3i c\u00f3 V\u1ea1n bi\u1ebfn l\u1ec7nh.";
            gameUB = "K\u00edch ho\u1ea1t ch\u1ee9c n\u0103ng n\u00e0y ph\u1ea3i t\u1ed1n 10.000 y\u00ean. B\u1ea1n c\u00f3 mu\u1ed1n k\u00edch ho\u1ea1t kh\u00f4ng ?";
            gameUC = "Nh\u1eadp m\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7";
            gameUD = "Nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd";
            gameUE = "B\u1ea1n ch\u01b0a nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd.";
            gameUF = "\u0110\u1ec3 l\u1ea5y m\u1eadt kh\u1ea9u cho '#'. B\u1ea1n ph\u1ea3i s\u1eed d\u1ee5ng s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd cho t\u00e0i kho\u1ea3n n\u00e0y.";
            gameUG = "\u0110\u1ed5i m\u1eadt kh\u1ea9u";
            gameUH = "Hu\u1ef7 b\u1ea3o v\u1ec7";
            gameUI = "M\u1eadt kh\u1ea9u c\u0169";
            gameUJ = "M\u1eadt kh\u1ea9u m\u1edbi";
            gameUK = "B\u1ea1n h\u1ecdc \u0111\u01b0\u1ee3c ";
            gameUL = "Nh\u1eadp th\u00f4ng b\u00e1o";
            gameUM = "Nh\u1eadp s\u1ed1 xu c\u1ea7n r\u00fat";
            gameUN = "Nh\u1eadp s\u1ed1 xu \u0111\u00f3ng g\u00f3p cho gia t\u1ed9c";
            gameUO = "Nh\u1eadp th\u00f4ng tin lo\u1ea1i th\u1ebb v\u00e0 m\u1ec7nh gi\u00e1";
            gameUP = "Nh\u1eadp th\u00f4ng tin s\u1ed1 seri v\u00e0 kho\u1ea3ng th\u1eddi gian n\u1ea1p";
            gameUQ = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng t\u00e1ch";
            gameUR = "M\u1ec7nh gi\u00e1";
            gameUS = "Lo\u1ea1i th\u1ebb";
            gameUT = "S\u1ed1 seri";
            gameUU = "Th\u1eddi gian n\u1ea1p";
            gameUV = "Ch\u1eb7n tin nh\u1eafn";
            gameUW = "B\u00e1o l\u1ed7i v\u1edbi Admin";
            gameUX = new String[]{"G\u00e1n ph\u00edm t\u1eaft", "G\u00e1n v\u00e0o 5 \u00f4 \u0111\u00e1nh"};
            gameUY = "G\u1eedi tin nh\u1eafn th\u00e0nh c\u00f4ng";
            gameUZ = "Ch\u00fac m\u1eebng b\u1ea1n \u0111\u00e3 g\u1edfi tin nh\u1eafn d\u1ef1 \u0111o\u00e1n th\u00e0nh c\u00f4ng.";
            gameVA = "Kh\u00f4ng th\u1ec3 g\u1eedi tin nh\u1eafn";
            gameVB = "Tin nh\u1eafn g\u1eedi kh\u00f4ng th\u00e0nh c\u00f4ng.";
            gameVC = "Kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 \u0111\u00f3ng g\u00f3p";
            gameVD = "S\u1ed1 l\u01b0\u1ee3ng t\u00e1ch kh\u00f4ng h\u1ee3p l\u1ec7.";
            gameVE = "Gi\u00e1 tr\u1ecb nh\u1eadp kh\u00f4ng h\u1ee3p l\u1ec7.";
            gameVF = "B\u1ea1n c\u00f3 mu\u1ed1n h\u1ee7y ch\u1ee9c n\u0103ng b\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n kh\u00f4ng ?";
            gameRC = "mu\u1ed1n th\u00e1ch \u0111\u1ea5u v\u1edbi b\u1ea1n \u1edf l\u00f4i \u0111\u00e0i. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            gameVG = "S\u1eafp x\u1ebfp theo gi\u00e1";
            gameVH = "S\u1eafp x\u1ebfp theo c\u1ea5p";
            gameVI = "S\u1eafp x\u1ebfp theo t\u00ean";
            gameVJ = "V\u1eadt ph\u1ea9m \u0111\u00e3 \u0111\u01b0\u1ee3c g\u1edfi b\u00e1n v\u00e0o gian h\u00e0ng";
            gameVK = "M\u1ee9c ph\u00ed cho m\u1ed7i l\u1ea7n b\u00e1n l\u00e0 5.000 xu";
            gameVM = "B\u1ea1n c\u00f3 mu\u1ed1n b\u00e1n v\u1eadt ph\u1ea9m v\u1edbi gi\u00e1 # xu kh\u00f4ng ?";
            gameVN = "B\u1ea1n c\u00f3 mu\u1ed1n mua v\u1eadt ph\u1ea9m v\u1edbi gi\u00e1 # xu kh\u00f4ng ?";
            gameVO = "Ng\u01b0\u1eddi b\u00e1n";
            gameVP = "c\u00f2n";
            gameVQ = "g\u1ea7n";
            gameVR = "h\u1ebft gi\u1edd";
            gameVS = new String[]{"\u0110\u00e1", "N\u00f3n", "V\u0169 kh\u00ed", "\u00c1o", "D\u00e2y chuy\u1ec1n", "G\u0103ng tay", "Nh\u1eabn", "Qu\u1ea7n", "Ng\u1ecdc b\u1ed9i", "Gi\u00e0y", "B\u00f9a", "Linh tinh"};
            gameVL = " V\u1eadt ph\u1ea9m b\u00e1n \u0111\u01b0\u1ee3c ch\u1ecbu thu\u1ebf l\u00e0 1%";
            gameKF = "Kinh nghi\u1ec7m";
            gameVT = "Th\u00f4ng b\u00e1o Server";
            gameVU = "Gi\u1edbi thi\u1ec7u b\u1ea1n b\u00e8";
            gameVV = "L\u1eadt h\u00ecnh";
            gameVW = "S\u1ed1 l\u01b0\u1ee3t l\u1eadt c\u00f2n l\u1ea1i c\u1ee7a b\u1ea1n l\u00e0: ";
            gameVX = "mu\u1ed1n th\u00e1ch \u0111\u1ea5u v\u1edbi b\u1ea1n v\u00e0 c\u1ea3 gia t\u1ed9c. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            gameVY = "Max options";
            gameVZ = "M\u1eddi ng\u01b0\u1eddi n\u00e0y";
            gameWA = "M\u1eddi t\u1ea5t c\u1ea3";
            gameWB = "'#' m\u1eddi b\u1ea1n v\u00e0o gia t\u1ed9c chi\u1ebfn. B\u1ea1n c\u00f3 mu\u1ed1n v\u00e0o kh\u00f4ng?";
            gameWC = "Nh\u1eadp t\u00ean th\u00e0nh vi\u00ean";
            gameWD = new String[][]{{"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 5.", "Ph\u00ed khai m\u1edf: 1.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 10.", "Ph\u00ed khai m\u1edf: 5.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 15.", "Ph\u00ed khai m\u1edf: 10.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 20.", "Ph\u00ed khai m\u1edf: 20.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 25.", "Ph\u00ed khai m\u1edf: 30.000.000 xu gia t\u1ed9c."}};
            gameWE = new String[]{"D\u00f9ng HP khi c\u00f2n d\u01b0\u1edbi: ", "D\u00f9ng MP khi c\u00f2n d\u01b0\u1edbi:", "D\u00f9ng th\u1ee9c \u0103n c\u1ea5p: ", "D\u00f9ng chi\u00eau h\u1ed5 tr\u1ee3", "D\u00f9ng khi\u00ean mana", "D\u00f9ng \u0111\u1ed1t qu\u00e1i & \u1ea9n th\u00e2n", "D\u00f9ng ph\u00e2n th\u00e2n", "Nh\u1eb7t y\u00ean", "Nh\u1eb7t HP, MP", "Nh\u1eb7t N.Li\u1ec7u(\u0110\u00e1)", "Luy\u1ec7n \u0111\u00e1 Max", "Nh\u1eb7t Trang B\u1ecb", "Nh\u1eb7t Trang B\u1ecb L\u1ea1", "Nh\u1eb7t VP Nhi\u1ec7m V\u1ee5", "Nh\u1eb7t VP S\u1ef1 Ki\u1ec7n", "Nh\u1eb7t All", "Nh\u1eb7t SVC", "Kh\u00f4ng nh\u1eb7t g\u00ec c\u1ea3", "Auto TTT", "AutoTTC", "ReMap", "T\u00e0n s\u00e1t map tr\u1ed1ng", "Auto Mua Th\u1ee9c \u0102n", "TS khi h\u1ebft MP", "Auto Reconnect", "Chuy\u1ec3n Map H\u1ebft Boss", "S\u0103n TATL", "\u0110\u00e1nh Qu\u00e1i Th\u01b0\u1eddng", "\u0110\u00e1nh Tinh Anh", "\u0110\u00e1nh Th\u1ee7 L\u0129nh", "C\u1ed9ng ti\u1ec1m n\u0103ng", "C\u1ed9ng k\u0129 n\u0103ng", "\u0110\u00e1nh theo nh\u00f3m", "N\u00e9 PK", "D\u00f9ng C\u1ed5 L\u1ec7nh", "Mua C\u1ed5 L\u1ec7nh"};
            gameWF = "D\u00f9ng ph\u00edm < v\u00e0 > \u0111\u1ec3 \u0111\u1ed5i gi\u00e1 tr\u1ecb";
            gameWG = "Ch\u1ea1m v\u00e0o \u00f4 th\u00f4ng s\u1ed1 \u0111\u1ec3 \u0111\u1ed5i gi\u00e1 tr\u1ecb";
            gameWH = "Kho\u1ea3ng c\u00e1ch qu\u00e1 xa, kh\u00f4ng th\u1ec3 ph\u1ee5c h\u1ed3i cho ng\u01b0\u1eddi kh\u00e1c \u0111\u01b0\u1ee3c";
            gameWI = "     Nh\u1eadp gi\u00e1 tr\u1ecb ph\u1ea7n tr\u0103m th\u1ea5p t\u1ed1i thi\u1ec3u            (T\u1eeb 10 \u0111\u1ebfn 90)";
            gameWJ = new String[]{"C\u1ea5p 1", "C\u1ea5p 10", "C\u1ea5p 20", "C\u1ea5p 30", "C\u1ea5p 40", "C\u1ea5p 50", "C\u1ea5p 60", "C\u1ea5p 70"};
            gameWK = new String[]{"C\u1ea5p 1", "C\u1ea5p 2", "C\u1ea5p 3", "C\u1ea5p 4", "C\u1ea5p 5", "C\u1ea5p 6", "C\u1ea5p 7", "C\u1ea5p 8", "C\u1ea5p 9", "C\u1ea5p 10", "C\u1ea5p 11", "C\u1ea5p 12"};
            gameWL = "T\u00e0i kho\u1ea3n \u0111ang \u0111\u01b0\u1ee3c b\u1ea3o v\u1ec7, vui l\u00f2ng m\u1edf kh\u00f3a.";
            gameWM = "Sinh l\u1ef1c";
            gameWN = "T\u00ean th\u00fa c\u01b0\u1ee1i";
            gameWO = new String[]{"Luy\u1ec7n th\u1ea1ch c\u1ea5p cao h\u01a1n b\u1eb1ng c\u00e1ch", "d\u00f9ng 9 th\u1ea1ch c\u00f9ng lo\u1ea1i ho\u1eb7c 3 th\u1ea1ch s\u01a1", "v\u00e0 \u0111\u00e1 11 ho\u1eb7c 3 th\u1ea1ch trung v\u00e0 \u0111\u00e1 12."};
            gameWP = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn T\u1eed tinh th\u1ea1ch s\u01a1 v\u00e0 trung c\u1ea5p";
            gameWQ = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1 v\u00e0 T\u1eed tinh th\u1ea1ch \u0111\u1ec3 luy\u1ec7n";
            gameWR = "Ch\u1ec9 c\u1ea7n d\u00f9ng 1 vi\u00ean \u0111\u00e1 \u0111\u1ec3 luy\u1ec7n";
            gameWS = "C\u1ea7n k\u1ebft h\u1ee3p 3 T\u1eed tinh th\u1ea1ch (trung) v\u00e0 \u0111\u00e1 12 ho\u1eb7c 3 t\u1eed tinh th\u1ea1ch (s\u01a1) \u0111\u00e1 11";
            gameWT = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0111\u00e1 c\u1ea5p 11 tr\u1edf l\u00ean";
            gameWU = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn T\u1eed thi\u00ean th\u1ea1ch c\u00f9ng lo\u1ea1i";
            gameWV = "Ph\u1ea3i c\u00f3 t\u1eeb 3 T\u1eed tinh th\u1ea1ch tr\u1edf l\u00ean m\u1edbi c\u00f3 th\u1ec3 luy\u1ec7n \u0111\u01b0\u1ee3c";
            gameWW = "S\u1ed1 l\u01b0\u1ee3ng T\u1eed tinh th\u1ea1ch qu\u00e1 nhi\u1ec1u";
            gameWX = "V\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng th\u1ec3 tinh luy\u1ec7n";
            gameWY = "C\u1ea7n ph\u1ea3i c\u00f3 \u0111\u1ee7 20 chuy\u1ec3n tinh th\u1ea1ch \u0111\u1ec3 d\u1ecbch chuy\u1ec3n trang bi";
            gameWZ = "V\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng d\u00f9ng trong d\u1ecbch chuy\u1ec3n";
            gameXA = "C\u1ea5t k\u1eb9o";
            gameXB = "\u0110\u1ed9 tinh luy\u1ec7n";
            gameXC = "\u0110\u1ed9ng c\u01a1";
            gameXD = "Nhi\u00ean li\u1ec7u";
            gameXE = "Cho k\u1eb9o";
            gameXF = new String[]{"t\u1eed tinh", "t\u1eed tinh th\u1ea1ch s\u01a1", "t\u1eed tinh th\u1ea1ch trung", "t\u1eed tinh th\u1ea1ch cao"};
            gameXG = "V\u1eadt ph\u1ea9m \u0111\u00e3 tinh luy\u1ec7n \u0111\u1ebfn m\u1ee9c t\u1ed1i \u0111a";
        } else if (languageID == 1) {
            gameAJ = "This gem can't roasting.";
            gameAI = "This gem reached max level.";
            gameAK = "Register account to keep your character safe. Do you want to register?";
            gameAL = "Hidden quest";
            gameAM = "- Get 1 aggressive point.";
            gameAN = "- Complete the cave of near school yard 1 times.";
            gameAO = "- Complete hunting wild beast 1 times.";
            gameAP = "- Upgrade equipment successful 1 times.";
            gameAQ = "- Complete daily quest 10 times.";
            gameAR = "- Get 1000 battlefield points.";
            gameAS = "- Complete seven beasts gate 1 times.";
            gameAT = "- Enjoy lucky card 3 times.";
            String[] var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "General Server"};
            gameAW = "Win rate";
            gameAX = "Your coin: ";
            gameAY = "Players: ";
            gameAZ = "Lucky draw";
            gameBA = "Join now";
            COUNTINUE = "Continue";
            NEW_ACC_ARLET = "Your account has not been verified. If you delete the game, or log another account, your character will lose playing forever.";
            NEW_PLAY = "New Play";
            COUNTINUE_PLAY = "Play";
            CHANGE_ACC = "Change Username";
            SERVER = "Server: ";
            gameBB = "rank";
            gameBC = "Challenge";
            gameBD = "Info";
            tips = new String[]{"Press change focus button to show all players on map", "For keyboard phones, assign shortcut keys 7,8,9 (or Q,W,E) to use skills.", "Berserk mode adds +2 agressive points.  Kill adds +1 agressive", "Sword, Kunai,and Blade increases Strength, Constitution, Dexterity", "Bow, Shuriken and Fan increases Chakra, Constitution, Dexterity", "Training as a team will earn experience and complete tasks faster", "Fighing other players on the battlefield will decrease combative points.", "When separated from the stone equipped, you will collect half amount of stone at the beginning.", "If you have enough action points, you can exchange coins from kin.", "The highest daily achievement in the arena will earn a reward.", "Find Rikudou to get into the arena.", "Precautionary measures cost money but will Increase the success rate of upgrading items", "When you reach Level 20, find Okanechan to received 10 gold bars.", "Gold bars will be split to 3 characters in 1 account"};
            gameBE = "Term";
            gameBG = "D\u1ee9a Nh\u1ecf..";
            gameBH = "Wait";
            gameBI = "Menu";
            gameBJ = "Need";
            gameBK = "Move to";
            LANGUAGE = "Language";
            gameBM = "Clear cache";
            LANGUAGES = new String[]{"Ti\u1ebfng vi\u1ec7t", "English"};
            var10000 = new String[]{"\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a", "\u1797\u17b6\u179f\u17b6\u17a2\u1784\u17cb\u1782\u17d2\u179b\u17c1\u179f"};
            gameBO = "Exit game to change the language ?";
            CLOSE = "Close";
            gameBQ = "Hide";
            gameBR = "Auto";
            gameBS = "Stand";
            gameBT = "by";
            gameBU = "Lock";
            gameBV = "Unlock";
            gameBW = "Seri number";
            gameBX = "Card code";
            gameBY = "On";
            gameBZ = "Off";
            gameCA = "Open link";
            gameCB = "Charge";
            gameCC = "Active";
            gameCD = "Config";
            DELETE = "Delete";
            gameCF = "View";
            gameCG = "Continue";
            gameCH = "Inventory code";
            gameCI = "Scratch card";
            gameCJ = "Next";
            gameCK = "Use";
            gameCL = "Sort";
            gameCM = "Throw it away";
            gameCN = "Split";
            gameCO = "Equipment has been split, you get ";
            YES = "Yes";
            gameCQ = "Get out";
            gameCR = "Get out";
            gameCS = "Withdraw coins";
            gameCT = "Store coins";
            gameCU = "Transfer coins";
            gameCV = "Store";
            gameCW = "Sell";
            gameCX = "Sell more";
            gameCY = "Sell all";
            gameCZ = "Price";
            gameDA = "Buy";
            gameDB = "Buy more";
            NO = "No";
            EXIT = "Exit";
            CHAT = "Chat";
            OK = "OK";
            USERNAME = "Account";
            PASSWORD = "Password";
            REPASS = "Re-input";
            gameDJ = "Account";
            gameDK = "Pass";
            gameDL = "re";
            RESTART = "Please restart game";
            REPASSWORD = "Re-input password";
            REMEMBER = "Remember";
            UNCHECK = "Uncheck";
            gameDQ = "Register";
            gameDR = "High Graphic";
            gameDS = "Low Graphic";
            NOT_INPUT_USERNAME = "Please input account name";
            NOT_SPEC_CHARACTER = "Account does not allow special characters.";
            NOT_INPUT_PASS1 = "You haven't added a password.";
            NOT_INPUT_PASS2 = "Your passwords do not match.";
            USERNAME_LENGHT = "Account name must have at least five characters";
            WRONG_PASSWORD = "Wrong password.";
            REGISTER_TEXT = new String[]{"To register with name", "you have to follow the game rule."};
            gameEA = "What operator are you using? (You can recheck it in Menu)";
            ASK_REG_NUM = "Are you using your phone number to create account ?";
            gameEC = "private message";
            gameED = new String[]{"message clan, group", "clan messages", "group message"};
            gameEE = "escort";
            gameEF = "Plus";
            gameEG = "Plus more";
            gameEH = "potential point";
            ACCEPT = "Accept";
            CANCEL = "Cancel";
            gameEK = "List";
            gameEL = "Time";
            gameEM = "Achievement";
            gameEN = "Max";
            gameEO = "Accumulate";
            CONNECTING = "Connecting";
            REGISTERING = "Registering";
            LOGGING = "Logging";
            gameES = "Not finished";
            gameET = "Time to finish";
            gameEU = "Teamwork";
            SELECT = "Select";
            gameEW = "Uncheck";
            gameEX = "Select items to view the information.";
            gameEY = "Assign";
            gameEZ = "Result";
            gameFA = "Review";
            gameFB = "Level";
            gameFC = "Level";
            gameFD = "Do you want to exit?";
            gameFE = "Please rename your character";
            gameFF = "This server is maintained or overloaded. Please try again later or choose another server.";
            gameFG = "Create";
            CHARNAME = "Name";
            gameFI = "Name of character you want to friend";
            gameFJ = "Friend link successful.";
            gameFK = "Loading... ";
            gameFL = "Close";
            gameFM = "Get reward";
            gameFN = "lucky gift";
            gameFO = "Inventory was expanded";
            gameFP = "Distance too far for escort, quest failed";
            gameFQ = "The escort was wounded, quest failed";
            gameFR = "forever";
            gameFS = "Not upgrade";
            gameFT = "Can not upgrade.";
            gameFU = "Use special items to upgrade";
            gameFV = "Train";
            gameFW = "Stone train successful, you get";
            gameFX = new String[]{"Just transfer same type equipment", " or higher.", "Will lock fitted after transformation.."};
            gameFY = "failure, you get";
            gameFZ = "Message sent, please wait for confirmation.";
            gameGA = "Can not send message. Please check you balance or restart the game.";
            gameGB = "Sending Coins";
            gameGC = "Start";
            gameGD = "Choose at least 2 stones or more";
            gameGE = "Choose the equipment that you want to split the Stone";
            gameGF = "Choose item and coins to exchange";
            gameGG = "Move to luggage to choose";
            CHANGE = "Change";
            gameGI = "Cell";
            gameGJ = "Cells";
            gameGK = new String[]{"Key Q", "Key W", "Key E"};
            gameGL = new String[]{"Key 7", "Key 8", "Key 9"};
            HAIR_STYLE = new String[][]{{"tomboy", "with brooch", "pony tail", "curly"}, {"head band", "afro", "samurai", "spike"}};
            gameGN = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment", "Mounts"};
            gameGO = new String[]{"Costume shop", "Inventory"};
            gameGP = new String[]{"Cap", "Inventory"};
            gameGQ = new String[]{"Cloth", "Inventory"};
            gameGR = new String[]{"Gloves", "Inventory"};
            gameGS = new String[]{"Pants", "Inventory"};
            gameGT = new String[]{"Shoes", "Inventory"};
            gameGU = new String[]{"Necklace", "Inventory"};
            gameGV = new String[]{"Ring", "Inventory"};
            gameGW = new String[]{"Gems", "Inventory"};
            gameGX = new String[]{"Charms", "Inventory"};
            gameGY = new String[]{"Weapons", "Inventory"};
            gameGZ = new String[]{"Medicine", "Inventory"};
            gameHA = new String[]{"Medicine", "Inventory"};
            gameHB = new String[]{"Food", "Inventory"};
            gameHC = new String[]{"Food", "Inventory"};
            gameHD = new String[]{"Upgrade", "Inventory"};
            gameHE = new String[]{"Stand", "Inventory"};
            gameHF = new String[]{"Transfer", "Inventory"};
            gameHG = new String[]{"Training Stone", "Inventory"};
            gameHH = new String[]{"Inventory", "Inventory"};
            gameHI = new String[]{"Shop", "Book Store", "Fashion Store", "Clan Store"};
            gameHK = new String[]{"Split Stone", "Inventory"};
            gameHL = new String[]{"Trade", "Inventory"};
            gameHM = new String[]{"Upgrade essence", "Inventory"};
            gameHN = new String[]{"Add attributes", "Inventory"};
            gameHO = new String[]{"Enhance equipment", "Inventory"};
            gameHP = new String[]{"Socketing", "Inventory"};
            gameHQ = new String[]{"Leveling gem", "Inventory"};
            gameHS = new String[]{"Gem Roasting", "Inventory"};
            gameHT = new String[]{"Extract gem", "Inventory"};
            gameHR = new String[]{"Completed quest", "Inventory"};
            gameXN = new String[]{"Pickup", "Inventory"};
            var10000 = new String[]{"Del", "Inventory"};
            gameXO = "Delete";
            gameXP = "Add";
            gameAU = "I will help decrease bad options of this gem.";
            gameAV = "I will help you extract gem from this item.";
            gameHU = new String[]{"- Use kin incase not enough coin", "- Move to inventory to choose stone", "- Amount of stones from 2 to 24"};
            gameHV = new String[]{"- Use coin incase not enough kin", "- Upgrading need Gold bar", "- Choose Equiptment and stone only", "Your equipment has reached max level"};
            gameHW = new String[]{"- Use coin incase not enough kin", "- Choose Equiptment and Gem"};
            gameHX = "Lock Transfer";
            gameHY = "- Train Stone to level";
            gameHZ = "- Need: # kin";
            gameKA = "- Need: # Gold bars";
            gameKB = "- Need: # coins";
            gameKC = "- Percentage of success.";
            gameKD = "(success ";
            gameKE = "Add";
            gameKG = "Locked";
            gameKH = "Killed";
            gameKI = "Arrest Beast";
            gameKJ = "Kill Elitez";
            gameKK = "Kill Chief";
            gameKL = "Protect the child";
            gameKM = "No lock";
            gameKN = "Expires";
            gameKO = "Price: # kin";
            gameKP = "Price: # coins";
            gameKQ = "Price: # clan coins";
            gameKR = "Price: # kin";
            gameKS = "Price: # gold bars";
            gameKT = "Gold bar";
            gameKU = "Do not have";
            gameKV = "Next level: level #";
            gameKW = "Current level: level #";
            gameKX = "Maximum level";
            gameKY = "Reached maximum level";
            gameKZ = "Require: level";
            gameMA = "Class: ";
            gameMB = new String[]{"Main quest", "Sub quest"};
            ME_TASK = "Quest";
            gameMD = "Obtain quest at";
            gameME = "White Side";
            gameMF = "Black Side";
            gameMG = "Neutral";
            gameMH = "team";
            gameMI = "Find team";
            gameMJ = "Your current aggressive points are ";
            gameMK = new String[]{"Friends", "Hostile"};
            gameML = "You are not friends with anyone";
            gameMM = "waiting confirmation";
            gameMN = "added you to friends list";
            gameMO = "You have added";
            gameMP = "to the list";
            gameMQ = "You and";
            gameMR = new String[]{"store", "Myself", "Map", "General", "Exit", "Jewellery", "Feature", "Pharmaceutical Key", "Pharmacy", "Grocery Key", "Grocery", "Strengthen", "Training", "Training key", "Inventory", "Split Equipment", "Area", "Trade", "Message"};
            gameMS = new String[]{"Passive Support", "Active use", "Active use", "Active use", "Active use"};
            gameMT = new String[]{"Character: ", "Agressive: ", "Level: ", "Class: ", "", "HP:", "MP: ", "Speed: ", "Attack: ", "Anti Fire: ", "Anti Ice: ", "Anti Wind: ", "Reduce Pain: ", "Accurate point:", "Dodge ability: ", "Critical: ", "Close combat strike back: ", "Anti chakra: ", "Anti chakra back: ", "Action points: "};
            gameMU = " times";
            gameMV = new String[]{"Genin", "Chunin", "Jounin", "Kage"};
            gameMW = new String[]{"Action point: ", "Weapon Fame: ", "Necklace Fame: ", "Ring Fame: ", "Gems Fame: ", "Charm Fame: ", "Hat Fame: ", "Cloth Fame: ", "Gloves Fame: ", "Pants Fame: ", "Shoes Fame: ", "Accomplish daily quest: ", "Arrest Beast: ", "Read the basic potential book: ", "Read the basic skill book: ", "Clan: ", "Cave time left: ", "Star Fame: ", "Wind Thunder Mooncake: ", "Ice Fire Mooncake: "};
            gameMX = new String[]{"Name: ", "Gender: ", "Hair: "};
            MENUGENDER = new String[]{"Female", "Male"};
            gameMZ = new String[]{"Strength", "Dexterity", "Constitution", "Chakra"};
            gameNA = "You were not killed by anyone.";
            gameNB = "You won #.";
            gameNC = "You lost #.";
            gameND = "Your fight match between you and # is over.";
            gameNE = new String[]{"", "Elitez", "Chief", "Beast"};
            gameNF = " try to kill you";
            gameNG = "Potential point";
            gameNH = "Skill point";
            gameNI = "Not enough MP to use";
            gameNJ = "Only select unlocked items";
            gameNK = "Only select unlocked items that haven't expired";
            gameNL = "Just choose Stones to train";
            gameNM = "Just choose Stone, Equipment and upgrade insurance.";
            gameNN = "Just choose Equipment and conversion items.";
            gameNO = "Can not upgrade";
            gameNP = "Maximum upgrade";
            gameNQ = "Only upgraded item or equipment to split.";
            gameNR = "Items for Trading are full.";
            gameNS = "Amount is Full.";
            gameNT = "Not enough points.";
            gameNU = "Please input added points.";
            gameNV = "You need to input card information.";
            gameNW = "You need to input card value information.";
            gameNX = "You need to enter serial number.";
            gameNY = "You need to enter topup times.";
            gameNZ = "You need to enter a name";
            gamePA = "Enter Points";
            gamePB = "Enter Coins";
            gamePC = "Enter quantity";
            INPUT_NICK = "Username";
            gamePE = "Coin";
            gamePF = "Kin";
            gamePG = "Gold bar";
            gamePH = "Put in inventory";
            gamePI = "Do you really want to dismissed this one?";
            gamePJ = "Expulsion of members will reduce Clan budgets (see details in Kanata NPC). Do you want to dismiss them?";
            gamePK = "Leaving clan will reduce your coins (see Kanata for details.)  Are you sure you want to leave?";
            gamePL = "After using this item, it will be locked. Do you want to use it?";
            gamePM = "Sold items can not be recovered. Do you want to sell this item?";
            gamePN = new String[][]{{"cap"}, {"wea", "pon"}, {"cloth"}, {"neck", "lace"}, {"glo", "ves"}, {"ring"}, {"pants"}, {"gems"}, {"shoes"}, {"charm"}, {"pet"}, {"mask"}, {"ninja", "yoroi"}, {"clan", "item"}, {"Emp", "ty"}, {"Ancient", "Book"}, {"Ar", "mor"}, {"Sad", "dle"}, {"Tas", "sels"}, {"Coro", "net"}, {"Eng", "ine"}, {"Sat", "nav"}, {"ECU", ""}, {"N20", ""}};
            gamePO = new String[]{"Not a student", "School: Hirosaki", "School: Ookaza", "School: Haruna"};
            gamePP = new String[]{"", "Attribute: Fire", "Attribute: Water", "Attribute: Wind", "", "", ""};
            gamePQ = "You got";
            gamePR = "You have not entered the amount of gold bars.";
            gamePS = "Can not sell upgraded equipment.";
            gamePT = "You don't have enough coins to move.";
            gamePU = "You don't have enough coins to store.";
            gamePV = "You don't have enough coins to withdraw.";
            gamePW = "You don't have enough gold bars to sell.";
            gamePX = new String[]{"Success,  equipped with level up ", "failed, return level of equipment", "equipment upgraded maximum", "equipment level"};
            gamePY = new String[]{"Success socketing", "Socketing has failed"};
            MONTH = "month";
            WEEK = "week";
            DAY = "day";
            HOUR = "hour";
            gameQD = "second";
            MINUTE = ",minute";
            gameQF = "Number of target";
            gameQG = "Range";
            gameQH = "MP cost";
            gameQI = "Cool down time";
            gameQJ = "You need at least two stones to train.";
            gameQK = "Gender does not match";
            gameQL = "Don't have any one else";
            gameQM = "Your level is too low";
            gameQN = "Stone has reached the maximum level";
            gameQO = "Your stones after leveling will be blocked. Would you like to continue?";
            gameQP = "You don't have enough coins to level stone";
            gameQQ = "You don't have enough gold bars to upgrade equipment";
            gameQR = "You don't have enough coins to upgrade equipment";
            gameQS = "Many training stones will be wasted. Are you sure you want to upgrade";
            gameQT = "After upgrade this item will be locked. Do you want to continue?";
            gameQU = "Can not split the unupgraded item.";
            gameQV = "Your luggage doesn't have enough space.";
            gameQW = "Do you really want to split this item?";
            gameQX = "Do you really want to convert?";
            gameQY = "Welcome to trading. Do you want to trade?";
            gameQZ = "Welcome to the clan. Do you want to join Clan '#' ?";
            gameRA = "Do you want to join this clan?";
            gameRB = "wants to fight with you. Do you accept?";
            gameRD = "invite you to Party. Do you want to join?";
            gameRE = "ask you to join their Party. Do you accept?";
            gameRF = "Convert successful.";
            gameRG = new String[]{"Gender: Female", "Gender: Male"};
            gameRH = "Area";
            gameRI = "Population";
            gameRJ = "Party";
            gameRK = "At this moment, you have not joined any Party.";
            gameRL = "times";
            gameRM = new String[]{"Info", "Member", "Warehouse", "Statistic", "Guardian"};
            gameRN = new String[]{"Clan: ", "Clanmaster: ", "Member: ", "Level: ", "Experience: ", "Budget: ", "Establish: ", "Donation: ", "Maintenance fee: ", "Upgrade fee: ", "Enter the Territory of Clan: remain ", "Week donation: ", "Use Clan card mark: remain "};
            CLAN_ACTIVITY = new String[]{"Coins at", "Establish clan, budget has", "expulsion, budget decrease", "clan contribution, budget increase", "withdraw clan budget, budget decrease", "Fee for maintain clan, budget decrease", "upgrade clan, budget decrease"};
            gameRP = "You are not a member of any clan";
            gameRQ = "Send to Clan Member";
            gameRR = new String[][]{{"Hirosaki School"}, {"Haruna School"}, {"Ookaza School"}, {"Village", "Kojin village", "Sanzu village", "Tone village", "Fish Village", "Chakumi Village", "Echigo Village", "Oshin Village"}, {"Area"}};
            gameRS = new String[]{"Cap", "Ring", "Cloth", "Necklace", "Gloves", "Ring", "Pants", "Gems", "Shoes", "Charm"};
            gameRT = new String[]{"Active hidden", "Active level"};
            gameRU = new String[]{"", "Fire", "Water", "Wind"};
            CHARINGFO = new String[]{"Character", "Level", "Jewellery"};
            gameRW = "You do not have any special skills.";
            gameRX = "You do not have any special weapons. Go to Menu/Status/Equipment to check";
            gameRY = "This item was locked.";
            gameRZ = "Items, accessories and stones";
            gameSA = "price (coin)";
            gameSB = "price (kin)";
            gameSC = "You are hungry, eat some more";
            gameSD = "You level is too low to use this item";
            gameSE = "Out off MP";
            gameSF = "Out off HP";
            gameSG = new String[]{"Trade", "Fight", "Berserker", "Add friend", "Invite to Party", "Recover", "Check info", "Private chat", "Invite to clan", "Request to join clan", "Block request to joint clan", "Auto recover", "C\u1ea5m Chat"};
            gameSH = "You are in ";
            gameSI = new String[]{"Let's find", " at ", " to get the quest.", "You have finished all quests this version, please wait for the next version."};
            gameSJ = new String[]{"Exhausted", "Starring", "Come back", "Revive now (1 Gold bar)"};
            gameSK = "After joining a class, you can receive any quest from the principal.";
            gameSL = "Create team";
            gameSM = "Leave team";
            gameSN = "Teamleader";
            gameSO = "Lock team";
            gameSP = "Unlock team";
            gameSQ = "Ask to join party.";
            gameSR = "Refresh";
            gameSS = "You are not a member of any team.";
            gameST = "Empty information.";
            gameSU = "Cannot find any Party now.";
            gameSV = new String[]{"PK normal", "PK team", "PK clan", "PK Berserker"};
            gameSW = new String[]{"PK status", "Friend", "Enemy", "Party", "Find party", "Clan", "Protect account", "Auto", "Sell Shinwa", "Upgrade essence", "Enhance equipment", "Add attributes"};
            gameSX = new String[]{"Map", "Quest", "Clan"};
            gameSY = new String[]{"Clan Master", "Chief Elder", "Elder", "Elite", "Member"};
            gameSZ = new String[]{"(CM)", "(CE)", "(ED)", "(EL)"};
            gameTA = new String[]{"Online only", "Left", "Notice ", " Contribute ", " Withdraw funds ", " Upgrade ", " Invite to territory ", "Unlock"};
            gameTB = "Sort by dedicating week";
            gameTC = new String[]{"Expulsion", "Transfer", "Make friend"};
            gameTD = " You are promoted to team leader.";
            gameTE = "You were kicked off of team.";
            gameTF = "Invite to team";
            gameTG = "Add";
            gameTH = "Inappropriated Weapons.";
            gameTI = "Do you want to delete this person from your friend list?";
            gameTJ = new String[]{"Go to school to upgrade your marks."};
            gameTK = new String[]{"Strength = Attack", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = MP"};
            gameTL = new String[]{"No need to upgrade strength", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = Attack, MP"};
            CLOSE_CURTAB = "Close current tab.";
            PUBLICCHAT = new String[]{"Public chat", "You can chat with people around you here."};
            PARTYCHAT = new String[]{"Same party", "You can chat with your Party member here."};
            GLOBALCHAT = new String[]{"Global chat", "You will lose 5 Gold Bars for each use.", "This message will broadcast to everybody.", "Your account will automatically be locked if you attempt to advestise any wap website, or use profanity."};
            CLANCHAT = new String[]{"Clan", "Yon can chat with Clanmates in this place"};
            gameTR = "Block global chat: ";
            gameTS = "Block private chat: ";
            gameTT = "Appoint";
            gameTU = "Dismiss";
            gameTV = "Expulsion";
            gameTW = "Maximum 6 digits.";
            gameTX = "Just allow number digit for protected password.";
            gameTY = "Protected password can not start with number 0.";
            gameTZ = "Wrong password.";
            gameUA = "To use this function, you have to have Multi Teleport Card.";
            gameUB = "To activate this function, you have to pay 10.000 kin. Do you want to activate?";
            gameUC = "Password";
            gameUD = "input the mobile number that you want to register";
            gameUE = "You did not input the number that you used to register this game before.";
            gameUF = "To get the password for account '#'. You must use the phone number used to register this account.";
            gameUG = "Change pass";
            gameUH = "Cancel protection";
            gameUI = "Old password";
            gameUJ = "New password";
            gameUK = "You have learned ";
            gameUL = "Input your message content";
            gameUM = "Input the amount of coin to withdraw";
            gameUN = "Input the coin amount to donate to the Clan.";
            gameUO = "Input type of card and value";
            gameUP = "Input serie number and time of charging.";
            gameUQ = "Input amount of split time.";
            gameUR = "Value";
            gameUS = "Type of card";
            gameUT = "Seri number";
            gameUU = "Time of charging";
            gameUV = "Block message";
            gameUW = "Submit this bug to Admin.";
            gameUX = new String[]{"Assign key", "Assign to 5 key"};
            gameUY = "Send message success.";
            gameUZ = "Congratulations! your choice is correct.";
            gameVA = "Can not send message.";
            gameVB = "Send failure.";
            gameVC = "Not enough coin to contribute";
            gameVD = "The amount to split is invalid.";
            gameVE = "invalid input value.";
            gameVF = "Do you want to cancel Protect account function?";
            gameRC = "wants to challenge you in the battle arena. Do you agree?";
            gameVG = "Sort by price";
            gameVH = "Sort by level";
            gameVI = "Sort by name";
            gameVJ = "Item is sent for trading";
            gameVK = "Trading fee is 5.000 coin";
            gameVM = "Do you want to sell item with # coins ?";
            gameVN = "Do you want to buy item with # coins ?";
            gameVO = "Seller";
            gameVP = "remain";
            gameVQ = "a few";
            gameVR = "seconds";
            gameVS = new String[]{"Stone", "Cap", "Weapon", "Cloth", "Necklace", "Gloves", "Rings", "Cloths", "Gems", "Shoes", "Charms", "Miscellaneous"};
            gameVL = "pay 1% of value as tax";
            gameKF = "Experience";
            gameVT = "Announcement";
            gameVU = "Invite friends";
            gameVV = "Choose card";
            gameVW = "Flip remaining: ";
            gameVX = "Challenges you and your clan. Do you agree ?";
            gameVY = "Max options";
            gameVZ = "Invite this person";
            gameWA = "Invite all";
            gameWB = "'#' invites you to join the clan war. Do you want to join?";
            gameWC = "Input member's name";
            gameWD = new String[][]{{"Requirement: Clan level 5", "Cost to Open: 1.000.000 clan coins."}, {"Requirement: Clan level 10.", "Cost to Open: 5.000.000 clan coins."}, {"Requirement: Clan level 15.", "Cost to Open: 10.000.000 clan coins."}, {"Requirement: Clan level 20.", "Cost to Open: 20.000.000 clan coins."}, {"Requirement: Clan level 25.", "Cost to Open: 30.000.000 clan coins."}};
            gameWE = new String[]{"HP: ", "MP: ", "Using food level: ", "Always using skill to support", "D\u00f9ng khi\u00ean mana", "D\u00f9ng \u0111\u1ed1t qu\u00e1i", "D\u00f9ng ph\u00e2n th\u00e2n", "Pick up Kins", "Pick up Hp, MP", "Pick up Material", "Luy\u1ec7n \u0111\u00e1 Max", "Nh\u1eb7t Trang B\u1ecb", "Nh\u1eb7t Trang B\u1ecb L\u1ea1", "Nh\u1eb7t VP Nhi\u1ec7m V\u1ee5", "Nh\u1eb7t VP S\u1ef1 Ki\u1ec7n", "Nh\u1eb7t All", "Nh\u1eb7t SVC", "Not picked up", "Auto TTT", "AutoTTC", "ReMap", "T\u00e0n s\u00e1t map tr\u1ed1ng", "Auto Mua Th\u1ee9c \u0102n", "TS khi h\u1ebft MP", "Auto Reconnect", "Next Map Null Boss", "S\u0103n TATL", "Hit Normal", "Hit Elitez", "Hit Chief", "C\u1ed9ng ti\u1ec1m n\u0103ng", "C\u1ed9ng k\u0129 n\u0103ng", "\u0110\u00e1nh theo nh\u00f3m", "N\u00e9 PK", "D\u00f9ng C\u1ed5 L\u1ec7nh", "Mua C\u1ed5 L\u1ec7nh"};
            gameWF = "Use button < and > to change value";
            gameWG = "Touch to change value";
            gameWH = "Distance is very far, Can not heal another people";
            gameWI = "Percent value is from 10 to 90";
            gameWJ = new String[]{"Level 1", "Level 10", "Level 20", "Level 30", "Level 40", "Level 50", "Level 60", "Level 70"};
            gameWK = new String[]{"Level 1", "Level 2", "Level 3", "Level 4", "Level 5", "Level 6", "Level 7", "Level 8", "Level 9", "Level 10", "Level 11", "Level 12"};
            gameWL = "Account required password, input password to unlock.";
            gameWM = "Vitality";
            gameWN = "Name of mounts";
            gameWO = new String[]{"Upgrade essence by using 9 essences", "of the same kind or 3 common essences", "and stone level 11 or 3 rare essences and stone level 12."};
            gameWP = "Only common essence and rare essence";
            gameWQ = "Only stone and essence to upgrade essence";
            gameWR = "Just only 1 stone to upgrade";
            gameWS = "Need to use 3 rare essences and stone level 12 or 3 common essences and stone level 11";
            gameWT = "Have to use stone level 11 and 12";
            gameWU = "Have to use essences of the same kind";
            gameWV = "Have to has 3 essences to Upgrade";
            gameWW = "Essences are excessive";
            gameWX = "This equipment can not Enhance";
            gameWY = "Not enough material";
            gameWZ = "This function is not available for this equipment";
            gameXA = "Save candy";
            gameXB = "Enhance level";
            gameXC = "Engine";
            gameXD = "Fuel";
            gameXE = "Give candy";
            gameXF = new String[]{"essence", "essence", "common essences", "rare essences"};
            gameXG = "Equipment enhanced to max level already";
        }
    }

    public static String gameAA(String var0, String var1) {
        return NinjaUtil.gameAA(var0, "#", var1);
    }
}
